/**
 * @file knn_cli.c
 * @brief Command-line interface parser and help renderer for gric-knn.
 */

#define _POSIX_C_SOURCE 200809L
#include "knn_cli.h"
#include "cli_colors.h"
#include "cli_opt.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

void knn_cli_print_usage(
    const char *progname)
{
    fprintf(stderr, "Usage: %s <input_data> <cluster_dir> [options]\n", progname);
}

void knn_cli_print_help(
    const char *progname)
{
    printf("%sNAME%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %sgric-knn%s - Out-of-core metric-pruned k-nearest neighbors solver\n\n",
           ansi_bold_green, ansi_reset);

    printf("%sUSAGE%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %s%s%s %s<input_data>%s %s<cluster_dir>%s %s[options]%s\n\n",
           ansi_bold_green, progname, ansi_reset,
           ansi_color_magenta, ansi_reset,
           ansi_color_magenta, ansi_reset,
           ansi_color_grey, ansi_reset);

    printf("%sDESCRIPTION%s\n", ansi_bold_cyan, ansi_reset);
    printf("  Identifies the k-nearest neighbors for each frame in a dataset using\n");
    printf("  the cluster anchors and metric distance bounds generated by Pass 1 "
           "(gric-cluster).\n");
    printf("  Maintains a strictly bounded resident RAM footprint while pruning 95-99%%\n");
    printf("  of high-dimensional distance evaluations.\n\n");

    size_t nopts = 0;
    const struct gric_opt *opts = knn_get_options(NULL, &nopts);
    gric_opt_print_help(stdout, progname, "<input_data> <cluster_dir> [options]", opts, nopts);

    printf("%sEXAMPLES%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %s$%s %s%s%s dataset.fits cluster_out/ -k 10 -dtmin 5\n",
           ansi_color_grey, ansi_reset, ansi_bold_green, progname, ansi_reset);
    printf("  %s$%s %s%s%s spiral.txt cluster_out/ -k 20 -eps 0.05 -progress\n",
           ansi_color_grey, ansi_reset, ansi_bold_green, progname, ansi_reset);
    printf("  %s$%s %s%s%s train_A.txt cluster_out/ -query test_C.txt -k 10\n\n",
           ansi_color_grey, ansi_reset, ansi_bold_green, progname, ansi_reset);
    cli_print_color_mode();
}

static void knn_cli_set_defaults(
    KnnConfig *config)
{
    memset(config, 0, sizeof(KnnConfig));
    config->k = 50;
    config->min_temporal_sep = 1;
    config->output_format = KNN_FORMAT_AUTO;
    config->progress_mode = 0;
    config->verbose_level = 1;
    config->use_reciprocal = 1;
    config->use_multi_pivot = 1;
    config->use_angular_bound = 1;
    config->use_trajectory = 0;
    config->use_rq8 = 0;
    config->use_rq8_adc = 1;
    config->use_rq8_sparse = 1;
    config->use_e8_quant = 0;
    config->use_e8_graph = 0;
    config->use_sq8 = 0;
    config->use_sq16 = -1;
    config->use_sq16_sparse = 1;
    config->use_sq16_sparse_lru = 0;
    config->use_eq16 = -1;
    config->use_eq16_adc = 1;
    config->use_eq16_sparse = 1;
    config->eq16_ratio = 0.05;
    config->use_rabitq = 0;
    config->rabitq_bits = 2;
    config->use_dcc_sq16 = 1;
    config->sq16_ratio = 0.05;
    config->use_memo = 1;
    config->use_batch_dist = 1;
    config->use_cluster_graph = 1;
    config->ef_cluster = 0;
    config->use_two_hop = 1;
    config->two_hop_seeds = 2;
    config->two_hop_max_cands = 32;
    config->no_txt = 1;
}

static int is_negation_key(
    const char *key)
{
    if (key == NULL)
    {
        return 0;
    }
    while (*key == '-')
    {
        key++;
    }
    return (strncmp(key, "no-", 3) == 0 || strncmp(key, "no_", 3) == 0 ||
            strncmp(key, "nosq", 4) == 0 || strncmp(key, "noeq", 4) == 0 ||
            strncmp(key, "norq", 4) == 0 || strncmp(key, "nomemo", 6) == 0 ||
            strncmp(key, "nobatch", 7) == 0 || strncmp(key, "noprof", 6) == 0 ||
            strncmp(key, "nomutual", 8) == 0 || strncmp(key, "nocache", 7) == 0 ||
            strncmp(key, "notrajectory", 12) == 0 || strncmp(key, "noreciprocal", 12) == 0);
}

static int cb_k(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->k = atoi(val);
    }
    return 1;
}

static int cb_dtmin(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->min_temporal_sep = atoi(val);
    }
    return 1;
}

static int cb_output(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->output_path = (char *)val;
        char *ext = strrchr(cfg->output_path, '.');
        if (ext != NULL && strcmp(ext, ".txt") == 0)
        {
            cfg->output_format = KNN_FORMAT_TXT;
            cfg->no_txt = 0;
        }
    }
    return 1;
}

static int cb_txt(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        if (is_negation_key(key))
        {
            cfg->no_txt = 1;
        }
        else
        {
            cfg->output_format = KNN_FORMAT_TXT;
            cfg->no_txt = 0;
        }
    }
    return 0;
}

static int cb_fits(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->output_format = KNN_FORMAT_FITS;
    }
    return 0;
}

static int cb_quiet(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->verbose_level = 0;
    }
    return 0;
}

static int cb_veryverbose(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->verbose_level = 2;
    }
    return 0;
}

static int cb_all_queries(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->refuse_unclustered = -1;
    }
    return 0;
}

static int cb_rq8(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        if (is_negation_key(key))
        {
            cfg->use_rq8 = 0;
            cfg->use_rq8_sparse = 0;
        }
        else
        {
            cfg->use_rq8 = 1;
            cfg->use_sq16 = 0;
            cfg->use_eq16 = 0;
            cfg->use_sq16_sparse = 0;
            cfg->use_sq16_sparse_lru = 0;
            cfg->use_sq8 = 0;
        }
    }
    return 0;
}

static int cb_rq8_sparse(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        if (is_negation_key(key) || strcmp(key, "-rq8-fastscan") == 0 ||
            strcmp(key, "--rq8-fastscan") == 0)
        {
            cfg->use_rq8_sparse = 0;
        }
        else
        {
            cfg->use_rq8 = 1;
            cfg->use_rq8_sparse = 1;
            cfg->use_sq16 = 0;
            cfg->use_eq16 = 0;
            cfg->use_sq16_sparse = 0;
            cfg->use_eq16_sparse = 0;
            cfg->use_sq8 = 0;
        }
    }
    return 0;
}

static int cb_rq8_save(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_rq8 = 1;
        cfg->use_sq16 = 0;
        cfg->use_eq16 = 0;
        cfg->use_sq8 = 0;
        cfg->rq8_save_path = (char *)val;
    }
    return 1;
}

static int cb_rq8_load(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_rq8 = 1;
        cfg->use_sq16 = 0;
        cfg->use_eq16 = 0;
        cfg->use_sq8 = 0;
        cfg->rq8_load_path = (char *)val;
    }
    return 1;
}

static int cb_rq8_approx(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_rq8 = 1;
        cfg->use_sq16 = 0;
        cfg->use_eq16 = 0;
        cfg->use_sq8 = 0;
        cfg->use_pq = 0;
        cfg->rq8_approx = 1;
    }
    return 0;
}

static int cb_e8_quant(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_rq8 = 1;
        cfg->use_e8_quant = 1;
        cfg->use_sq16 = 0;
        cfg->use_eq16 = 0;
        cfg->use_sq16_sparse = 0;
        cfg->use_sq16_sparse_lru = 0;
        cfg->use_eq16_sparse = 0;
        cfg->use_sq8 = 0;
    }
    return 0;
}

static int cb_e8_graph(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_rq8 = 1;
        cfg->use_e8_quant = 1;
        cfg->use_e8_graph = 1;
        cfg->use_sq16 = 0;
        cfg->use_eq16 = 0;
        cfg->use_sq16_sparse = 0;
        cfg->use_sq16_sparse_lru = 0;
        cfg->use_eq16_sparse = 0;
        cfg->use_sq8 = 0;
    }
    return 0;
}

static int cb_sq8(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        if (is_negation_key(key))
        {
            cfg->use_sq8 = 0;
        }
        else
        {
            cfg->use_sq8 = 1;
            cfg->use_sq16 = 0;
            cfg->use_eq16 = 0;
            cfg->use_rq8 = 0;
        }
    }
    return 0;
}

static int cb_sq8_save(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_sq8 = 1;
        cfg->use_rq8 = 0;
        cfg->use_sq16 = 0;
        cfg->use_eq16 = 0;
        cfg->sq8_save_path = (char *)val;
    }
    return 1;
}

static int cb_sq8_load(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_sq8 = 1;
        cfg->use_rq8 = 0;
        cfg->use_sq16 = 0;
        cfg->use_eq16 = 0;
        cfg->sq8_load_path = (char *)val;
    }
    return 1;
}

static int cb_sq8_approx(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->sq8_approx = 1;
    }
    return 0;
}

static int cb_sq16_approx(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->sq16_approx = 1;
    }
    return 0;
}

static int cb_eq16_approx(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->eq16_approx = 1;
    }
    return 0;
}

static int cb_rabitq_approx(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->rabitq_approx = 1;
    }
    return 0;
}

static int cb_sq16(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        if (is_negation_key(key))
        {
            cfg->use_sq16 = 0;
        }
        else
        {
            cfg->use_sq16 = 1;
            cfg->use_sq8 = 0;
            cfg->use_eq16 = 0;
            cfg->use_rq8 = 0;
        }
    }
    return 0;
}

static int cb_sq16_save(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_sq16 = 1;
        cfg->use_sq8 = 0;
        cfg->use_eq16 = 0;
        cfg->use_rq8 = 0;
        cfg->sq16_save_path = (char *)val;
    }
    return 1;
}

static int cb_sq16_load(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_sq16 = 1;
        cfg->use_sq8 = 0;
        cfg->use_eq16 = 0;
        cfg->use_rq8 = 0;
        cfg->sq16_load_path = (char *)val;
    }
    return 1;
}

static int cb_eq16(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        if (is_negation_key(key))
        {
            cfg->use_eq16 = 0;
        }
        else
        {
            cfg->use_eq16 = 1;
            cfg->use_sq8 = 0;
            cfg->use_sq16 = 0;
            cfg->use_rq8 = 0;
        }
    }
    return 0;
}

static int cb_eq16_save(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_eq16 = 1;
        cfg->use_sq8 = 0;
        cfg->use_sq16 = 0;
        cfg->use_rq8 = 0;
        cfg->eq16_save_path = (char *)val;
    }
    return 1;
}

static int cb_eq16_load(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_eq16 = 1;
        cfg->use_sq8 = 0;
        cfg->use_sq16 = 0;
        cfg->use_rq8 = 0;
        cfg->eq16_load_path = (char *)val;
    }
    return 1;
}

static int cb_rabitq(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        if (is_negation_key(key))
        {
            cfg->use_rabitq = 0;
        }
        else
        {
            cfg->use_rabitq = 1;
            cfg->use_sq8 = 0;
            cfg->use_sq16 = 0;
            cfg->use_eq16 = 0;
            cfg->use_rq8 = 0;
        }
    }
    return 0;
}

static int cb_rabitq_save(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_rabitq = 1;
        cfg->use_sq8 = 0;
        cfg->use_sq16 = 0;
        cfg->use_eq16 = 0;
        cfg->use_rq8 = 0;
        cfg->rabitq_save_path = (char *)val;
    }
    return 1;
}

static int cb_rabitq_load(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_rabitq = 1;
        cfg->use_sq8 = 0;
        cfg->use_sq16 = 0;
        cfg->use_eq16 = 0;
        cfg->use_rq8 = 0;
        cfg->rabitq_load_path = (char *)val;
    }
    return 1;
}

static int cb_gpu(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_gpu = is_negation_key(key) ? 0 : 1;
    }
    return 0;
}

static int cb_cpu(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_gpu = 0;
    }
    return 0;
}

static int cb_gpu_device(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_gpu = 1;
        cfg->gpu_device_id = atoi(val);
    }
    return 1;
}

static int cb_gpu_batch_size(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_gpu = 1;
        if (val != NULL && val[0] != '-')
        {
            cfg->gpu_batch_size = atoi(val);
            return 1;
        }
        cfg->gpu_batch_size = 512;
    }
    return 0;
}

static int cb_gpu_nprobe(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    if (val == NULL)
    {
        return -1;
    }
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_gpu = 1;
        cfg->gpu_nprobe = atoi(val);
    }
    return 1;
}

static int cb_gpu_bf(
    const char *key,
    const char *val,
    void       *ctx)
{
    (void)key;
    (void)val;
    KnnConfig *cfg = (KnnConfig *)ctx;
    if (cfg != NULL)
    {
        cfg->use_gpu = 1;
        cfg->use_gpu_bruteforce = 1;
    }
    return 0;
}

const struct gric_opt *knn_get_options(
    KnnConfig *config,
    size_t    *nopts)
{
    static struct gric_opt opts[] = {
        /* Core Search */
        {"k", 'k', GRIC_OPT_CUSTOM, (void *)cb_k, 0, "50", "<int>",
         "Number of nearest neighbors to find", "Core Search", NULL, 0},
        {"query", '\0', GRIC_OPT_STRING, NULL, 0, "", "<path>",
         "External query dataset (cross-dataset k-NN mode)", "Core Search", NULL, 0},
        {"output", 'o', GRIC_OPT_CUSTOM, (void *)cb_output, 0, "", "<path>",
         "Output file path", "Output & Format", "out", 0},
        {"dtmin", '\0', GRIC_OPT_CUSTOM, (void *)cb_dtmin, 0, "1", "<int>",
         "Min frame index separation |i - j| >= dtmin", "Core Search", NULL, 0},
        {"past", '\0', GRIC_OPT_FLAG, NULL, 0, "0", NULL,
         "Search only among preceding frames (j < i)", "Core Search", NULL, 0},
        {"future", '\0', GRIC_OPT_FLAG, NULL, 0, "0", NULL,
         "Search only among subsequent frames (j > i)", "Core Search", NULL, 0},
        {"eps", '\0', GRIC_OPT_DOUBLE, NULL, 0, "0.0", "<float>",
         "(1+eps)-ANN relaxation slack factor", "Core Search", "epsilon", 0},
        {"rlim", '\0', GRIC_OPT_DOUBLE, NULL, 0, "0.0", "<float>",
         "Maximum distance cutoff (ignore neighbors beyond rlim)", "Core Search", NULL, 0},
        {"double", '\0', GRIC_OPT_FLAG, NULL, 0, "0", NULL,
         "Force 64-bit double precision distance calculations", "Core Search", NULL, 0},
        {"all-queries", '\0', GRIC_OPT_CUSTOM, (void *)cb_all_queries, 0, "0", NULL,
         "Do not refuse out-of-cluster queries (exhaustive)", "Core Search", "all_queries", 0},

        /* Output & Format */
        {"fits", '\0', GRIC_OPT_CUSTOM, (void *)cb_fits, 0, "0", NULL,
         "Force FITS output format", "Output & Format", NULL, 0},
        {"txt", '\0', GRIC_OPT_CUSTOM, (void *)cb_txt, 0, "0", NULL,
         "Force ASCII text output format", "Output & Format", NULL, 1},
        {"no-txt", '\0', GRIC_OPT_CUSTOM, (void *)cb_txt, 0, "1", NULL,
         "Disable ASCII text output", "Output & Format", "notxt,no_txt", 0},
        {"progress", 'p', GRIC_OPT_FLAG, NULL, 0, "0", NULL,
         "Display live console progress bar", "Output & Format", NULL, 0},
        {"verbose", 'v', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "Verbosity level", "Output & Format", NULL, 0},
        {"veryverbose", '\0', GRIC_OPT_CUSTOM, (void *)cb_veryverbose, 0, "0", NULL,
         "Very verbose logging", "Output & Format", "vv", 0},
        {"quiet", 'q', GRIC_OPT_CUSTOM, (void *)cb_quiet, 0, "0", NULL,
         "Quiet mode (disable logging)", "Output & Format", NULL, 0},
        {"prof", '\0', GRIC_OPT_STRING, NULL, 0, "", "<path>",
         "Explicit dataset profile file (.gricprof)", "Output & Format", "profile", 0},
        {"no-prof", '\0', GRIC_OPT_FLAG, NULL, 0, "0", NULL,
         "Disable auto-loading of .gricprof file", "Output & Format", "noprof,no_prof", 0},
        {"no-mutual", '\0', GRIC_OPT_FLAG, NULL, 0, "0", NULL,
         "Disable knn_mutual_dists.bin calculation", "Output & Format", "nomutual,no_mutual", 0},
        {"no-cache", '\0', GRIC_OPT_FLAG, NULL, 0, "0", NULL,
         "Disable caching of dataset in resident RAM", "Output & Format", "nocache,no_cache", 0},

        /* Metric Pruning */
        {"multipivot", '\0', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "Enable Multi-Anchor Pivot Bounding (AESA)", "Metric Pruning",
         "multi_pivot,multi-pivot", 1},
        {"angular", '\0', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "Enable Angular Cosine Directional Bounding", "Metric Pruning", "direction", 1},
        {"trajectory", '\0', GRIC_OPT_FLAG, NULL, 0, "0", NULL,
         "Enable Trajectory Momentum", "Metric Pruning", NULL, 1},
        {"reciprocal", '\0', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "Enable Symmetric Distance Reciprocal Push", "Metric Pruning", NULL, 1},
        {"approx", '\0', GRIC_OPT_FLAG, NULL, 0, "0", NULL,
         "Fast Approximate Graph Search", "Metric Pruning", "fast", 0},
        {"ef-search", '\0', GRIC_OPT_INT, NULL, 0, "0", "<int>",
         "Size of priority queue for approx search", "Metric Pruning", "ef", 0},
        {"cluster-graph", '\0', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "Enable Graph-Guided Cluster Routing", "Metric Pruning", NULL, 1},
        {"ef-cluster", '\0', GRIC_OPT_INT, NULL, 0, "0", "<int>",
         "Max clusters to evaluate in graph routing", "Metric Pruning", NULL, 0},
        {"two-hop", '\0', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "Enable 2-Hop Candidate Injection", "Metric Pruning", NULL, 1},
        {"two-hop-seeds", '\0', GRIC_OPT_INT, NULL, 0, "2", "<int>",
         "Number of top seeds to expand in 2-hop search", "Metric Pruning", NULL, 0},
        {"two-hop-max", '\0', GRIC_OPT_INT, NULL, 0, "32", "<int>",
         "Max 2-hop candidates evaluated per query", "Metric Pruning", NULL, 0},

        /* Quantization & FastScan */
        {"rq8", '\0', GRIC_OPT_CUSTOM, (void *)cb_rq8, 0, "0", NULL,
         "Residual Quantization (8-bit)", "Quantization", NULL, 1},
        {"rq8-adc", '\0', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "Asymmetric Distance Computation for RQ8", "Quantization", NULL, 1},
        {"rq8-sparse", '\0', GRIC_OPT_CUSTOM, (void *)cb_rq8_sparse, 0, "1", NULL,
         "Sparse on-demand FastScan for RQ8", "Quantization", "rq8-fastscan", 1},
        {"rq8-save", '\0', GRIC_OPT_CUSTOM, (void *)cb_rq8_save, 0, "", "<path>",
         "Save computed RQ8 codebook and codes", "Quantization", NULL, 0},
        {"rq8-load", '\0', GRIC_OPT_CUSTOM, (void *)cb_rq8_load, 0, "", "<path>",
         "Load precomputed RQ8 codes", "Quantization", NULL, 0},
        {"rq8-approx", '\0', GRIC_OPT_CUSTOM, (void *)cb_rq8_approx, 0, "0", NULL,
         "Approximate non-bounding distance mode for RQ8", "Quantization", NULL, 0},
        {"e8-quant", '\0', GRIC_OPT_CUSTOM, (void *)cb_e8_quant, 0, "0", NULL,
         "E8 Gosset lattice quantization", "Quantization", "rq8-e8,e8", 0},
        {"e8-graph", '\0', GRIC_OPT_CUSTOM, (void *)cb_e8_graph, 0, "0", NULL,
         "E8 proximity graph routing", "Quantization", NULL, 0},
        {"sq8", '\0', GRIC_OPT_CUSTOM, (void *)cb_sq8, 0, "0", NULL,
         "Scalar 8-bit quantization", "Quantization", NULL, 1},
        {"sq8-save", '\0', GRIC_OPT_CUSTOM, (void *)cb_sq8_save, 0, "", "<path>",
         "Save SQ8 quantized codes", "Quantization", NULL, 0},
        {"sq8-load", '\0', GRIC_OPT_CUSTOM, (void *)cb_sq8_load, 0, "", "<path>",
         "Load precomputed SQ8 codes", "Quantization", NULL, 0},
        {"sq8-approx", '\0', GRIC_OPT_CUSTOM, (void *)cb_sq8_approx, 0, "0", NULL,
         "Enable approximate lower bound in SQ8", "Quantization", NULL, 0},
        {"sq16", '\0', GRIC_OPT_CUSTOM, (void *)cb_sq16, 0, "auto", NULL,
         "Scalar 16-bit quantization", "Quantization", NULL, 1},
        {"sq16-sparse", '\0', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "On-demand FastScan block transpose", "Quantization", NULL, 1},
        {"sq16-sparse-lru", '\0', GRIC_OPT_FLAG, NULL, 0, "0", NULL,
         "LRU Transposed FastScan cache", "Quantization", NULL, 1},
        {"sq16-save", '\0', GRIC_OPT_CUSTOM, (void *)cb_sq16_save, 0, "", "<path>",
         "Save SQ16 quantized codes", "Quantization", NULL, 0},
        {"sq16-load", '\0', GRIC_OPT_CUSTOM, (void *)cb_sq16_load, 0, "", "<path>",
         "Load precomputed SQ16 codes", "Quantization", NULL, 0},
        {"sq16-approx", '\0', GRIC_OPT_CUSTOM, (void *)cb_sq16_approx, 0, "0", NULL,
         "Enable approximate lower bound in SQ16", "Quantization", NULL, 0},
        {"sq16-ratio", '\0', GRIC_OPT_DOUBLE, NULL, 0, "0.05", "<ratio>",
         "Scale ratio bound for SQ16", "Quantization", NULL, 0},
        {"eq16", '\0', GRIC_OPT_CUSTOM, (void *)cb_eq16, 0, "auto", NULL,
         "Exact 16-bit block lattice quantization", "Quantization", NULL, 1},
        {"eq16-adc", '\0', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "Asymmetric distance computation for EQ16", "Quantization", NULL, 1},
        {"eq16-sparse", '\0', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "SparseCache for EQ16", "Quantization", NULL, 1},
        {"eq16-save", '\0', GRIC_OPT_CUSTOM, (void *)cb_eq16_save, 0, "", "<path>",
         "Save EQ16 quantized codes", "Quantization", NULL, 0},
        {"eq16-load", '\0', GRIC_OPT_CUSTOM, (void *)cb_eq16_load, 0, "", "<path>",
         "Load precomputed EQ16 codes", "Quantization", NULL, 0},
        {"eq16-approx", '\0', GRIC_OPT_CUSTOM, (void *)cb_eq16_approx, 0, "0", NULL,
         "Enable approximate lower bound in EQ16", "Quantization", NULL, 0},
        {"eq16-ratio", '\0', GRIC_OPT_DOUBLE, NULL, 0, "0.05", "<ratio>",
         "Scale ratio bound for EQ16", "Quantization", NULL, 0},
        {"rabitq", '\0', GRIC_OPT_CUSTOM, (void *)cb_rabitq, 0, "0", NULL,
         "RaBitQ randomized bit quantization", "Quantization", NULL, 1},
        {"rabitq-bits", '\0', GRIC_OPT_INT, NULL, 0, "2", "<int>",
         "RaBitQ bits per dimension", "Quantization", NULL, 0},
        {"rabitq-save", '\0', GRIC_OPT_CUSTOM, (void *)cb_rabitq_save, 0, "", "<path>",
         "Save RaBitQ quantized codes", "Quantization", NULL, 0},
        {"rabitq-load", '\0', GRIC_OPT_CUSTOM, (void *)cb_rabitq_load, 0, "", "<path>",
         "Load precomputed RaBitQ codes", "Quantization", NULL, 0},
        {"rabitq-approx", '\0', GRIC_OPT_CUSTOM, (void *)cb_rabitq_approx, 0, "0", NULL,
         "Enable approximate lower bound in RaBitQ", "Quantization", NULL, 0},
        {"dcc-sq16", '\0', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "Use 16-bit quantized DCC matrix", "Quantization", NULL, 1},
        {"memo", '\0', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "Quantized candidate memoization table", "Quantization", "use_memo,nomemo", 1},
        {"batch-dist", '\0', GRIC_OPT_FLAG, NULL, 0, "1", NULL,
         "Multi-vector SIMD batching", "Quantization", "batchdist,nobatchdist", 1},

        /* Execution & GPU */
        {"nthreads", '\0', GRIC_OPT_INT, NULL, 0, "0", "<int>",
         "Number of OpenMP worker threads", "Execution & GPU", NULL, 0},
        {"gpu", '\0', GRIC_OPT_CUSTOM, (void *)cb_gpu, 0, "0", NULL,
         "Enable CUDA GPU acceleration", "Execution & GPU", NULL, 1},
        {"cpu", '\0', GRIC_OPT_CUSTOM, (void *)cb_cpu, 0, "1", NULL,
         "Force CPU execution (disable GPU)", "Execution & GPU", NULL, 0},
        {"gpu-device", '\0', GRIC_OPT_CUSTOM, (void *)cb_gpu_device, 0, "0", "<id>",
         "Select GPU device ID", "Execution & GPU", NULL, 0},
        {"gpu-batch-size", '\0', GRIC_OPT_CUSTOM, (void *)cb_gpu_batch_size, 0, "auto", "<size>",
         "Micro-batch size for GPU queries", "Execution & GPU", "gpu-micro-batch", 0},
        {"gpu-nprobe", '\0', GRIC_OPT_CUSTOM, (void *)cb_gpu_nprobe, 0, "auto", "<int>",
         "Max clusters to probe on GPU", "Execution & GPU", "nprobe", 0},
        {"gpu-bf", '\0', GRIC_OPT_CUSTOM, (void *)cb_gpu_bf, 0, "0", NULL,
         "Force dense GEMM brute-force on GPU", "Execution & GPU", "gpu-brute-force", 0}
    };

    size_t count = sizeof(opts) / sizeof(opts[0]);

    if (config != NULL)
    {
        for (size_t ii = 0; ii < count; ii++)
        {
            const char *name = opts[ii].long_name;
            if (strcmp(name, "query") == 0)
                opts[ii].target = &config->query_data_path;
            else if (strcmp(name, "past") == 0)
                opts[ii].target = &config->past_only;
            else if (strcmp(name, "future") == 0)
                opts[ii].target = &config->future_only;
            else if (strcmp(name, "eps") == 0)
                opts[ii].target = &config->epsilon;
            else if (strcmp(name, "rlim") == 0)
                opts[ii].target = &config->rlim_cutoff;
            else if (strcmp(name, "double") == 0)
                opts[ii].target = &config->use_double;
            else if (strcmp(name, "progress") == 0)
                opts[ii].target = &config->progress_mode;
            else if (strcmp(name, "verbose") == 0)
                opts[ii].target = &config->verbose_level;
            else if (strcmp(name, "prof") == 0)
                opts[ii].target = &config->prof_filename;
            else if (strcmp(name, "no-prof") == 0)
                opts[ii].target = &config->no_prof;
            else if (strcmp(name, "no-mutual") == 0)
                opts[ii].target = &config->no_mutual;
            else if (strcmp(name, "no-cache") == 0)
                opts[ii].target = &config->no_cache_dataset;
            else if (strcmp(name, "multipivot") == 0)
                opts[ii].target = &config->use_multi_pivot;
            else if (strcmp(name, "angular") == 0)
                opts[ii].target = &config->use_angular_bound;
            else if (strcmp(name, "trajectory") == 0)
                opts[ii].target = &config->use_trajectory;
            else if (strcmp(name, "reciprocal") == 0)
                opts[ii].target = &config->use_reciprocal;
            else if (strcmp(name, "approx") == 0)
                opts[ii].target = &config->approx_mode;
            else if (strcmp(name, "ef-search") == 0)
                opts[ii].target = &config->ef_search;
            else if (strcmp(name, "cluster-graph") == 0)
                opts[ii].target = &config->use_cluster_graph;
            else if (strcmp(name, "ef-cluster") == 0)
                opts[ii].target = &config->ef_cluster;
            else if (strcmp(name, "two-hop") == 0)
                opts[ii].target = &config->use_two_hop;
            else if (strcmp(name, "two-hop-seeds") == 0)
                opts[ii].target = &config->two_hop_seeds;
            else if (strcmp(name, "two-hop-max") == 0)
                opts[ii].target = &config->two_hop_max_cands;
            else if (strcmp(name, "rq8-adc") == 0)
                opts[ii].target = &config->use_rq8_adc;
            else if (strcmp(name, "sq16-sparse") == 0)
                opts[ii].target = &config->use_sq16_sparse;
            else if (strcmp(name, "sq16-sparse-lru") == 0)
                opts[ii].target = &config->use_sq16_sparse_lru;
            else if (strcmp(name, "sq16-ratio") == 0)
                opts[ii].target = &config->sq16_ratio;
            else if (strcmp(name, "eq16-adc") == 0)
                opts[ii].target = &config->use_eq16_adc;
            else if (strcmp(name, "eq16-sparse") == 0)
                opts[ii].target = &config->use_eq16_sparse;
            else if (strcmp(name, "eq16-ratio") == 0)
                opts[ii].target = &config->eq16_ratio;
            else if (strcmp(name, "rabitq-bits") == 0)
                opts[ii].target = &config->rabitq_bits;
            else if (strcmp(name, "dcc-sq16") == 0)
                opts[ii].target = &config->use_dcc_sq16;
            else if (strcmp(name, "memo") == 0)
                opts[ii].target = &config->use_memo;
            else if (strcmp(name, "batch-dist") == 0)
                opts[ii].target = &config->use_batch_dist;
            else if (strcmp(name, "nthreads") == 0)
                opts[ii].target = &config->nthreads;
        }
    }

    if (nopts != NULL)
    {
        *nopts = count;
    }
    return opts;
}

static int knn_cli_parse_positional(
    char       *arg,
    KnnConfig  *config,
    const char *progname)
{
    if (config->input_data_path == NULL)
    {
        config->input_data_path = arg;
    }
    else if (config->cluster_dir == NULL)
    {
        config->cluster_dir = arg;
    }
    else
    {
        fprintf(stderr, "Error: Too many positional arguments\n");
        knn_cli_print_usage(progname);
        return 1;
    }
    return 0;
}

static int knn_cli_validate(
    KnnConfig  *config,
    const char *progname,
    int         k_set,
    int         dtmin_set)
{
    if (config->input_data_path == NULL || config->cluster_dir == NULL)
    {
        fprintf(stderr, "Error: Missing required arguments <input_data> and <cluster_dir>\n");
        knn_cli_print_usage(progname);
        return 1;
    }

    if (config->k <= 0)
    {
        fprintf(stderr, "Error: k must be >= 1\n");
        return 1;
    }

    if (config->query_data_path != NULL)
    {
        if (!k_set)
        {
            config->k = 30;
        }
        if (!dtmin_set)
        {
            config->min_temporal_sep = 0;
        }
        config->use_reciprocal = 0;
    }

    if (config->past_only || config->future_only)
    {
        config->use_reciprocal = 0;
    }

    return 0;
}

int knn_cli_parse(
    int        argc,
    char     **argv,
    KnnConfig *config)
{
    if (config == NULL)
    {
        return 1;
    }

    knn_cli_set_defaults(config);

    int k_explicitly_set = 0;
    int dtmin_explicitly_set = 0;
    size_t nopts = 0;
    const struct gric_opt *opts = knn_get_options(config, &nopts);
    int arg_idx = 1;

    while (arg_idx < argc)
    {
        if (strcmp(argv[arg_idx], "-h") == 0 || strcmp(argv[arg_idx], "--help") == 0)
        {
            knn_cli_print_help(argv[0]);
            return 2;
        }

        const char *tok = argv[arg_idx];
        int res = gric_opt_parse_arg(argc, argv, &arg_idx, opts, nopts, config);
        if (res == 1)
        {
            if (strncmp(tok, "-k", 2) == 0 || strncmp(tok, "--k", 3) == 0)
            {
                k_explicitly_set = 1;
            }
            if (strncmp(tok, "-dtmin", 6) == 0 || strncmp(tok, "--dtmin", 7) == 0)
            {
                dtmin_explicitly_set = 1;
            }
            continue;
        }
        else if (res < 0)
        {
            knn_cli_print_usage(argv[0]);
            return 1;
        }

        if (argv[arg_idx][0] == '-' && !isdigit(argv[arg_idx][1]))
        {
            fprintf(stderr, "Error: Unknown option '%s'\n", argv[arg_idx]);
            knn_cli_print_usage(argv[0]);
            return 1;
        }

        if (knn_cli_parse_positional(argv[arg_idx], config, argv[0]) != 0)
        {
            return 1;
        }
        arg_idx++;
    } // while arg_idx

    return knn_cli_validate(config, argv[0], k_explicitly_set, dtmin_explicitly_set);
}

void knn_cli_print_banner(
    const KnnConfig *config)
{
    printf("%sStarting gric-knn: Out-of-Core Metric-Pruned k-NN Solver%s\n",
           ansi_bold_green, ansi_reset);
    printf("  Dataset (A):   %s\n", config->input_data_path);
    printf("  Cluster Dir:   %s\n", config->cluster_dir);
    if (config->query_data_path != NULL)
    {
        printf("  Query Set (C): %s (Cross-Dataset Mode)\n", config->query_data_path);
    }
    printf("  k Neighbors:   %d\n", config->k);
    if (config->query_data_path == NULL)
    {
        printf("  Min Temp Sep:  %d frames\n", config->min_temporal_sep);
        if (config->past_only)
        {
            printf("  Direction:     Past-only (j < i)\n");
        }
        else if (config->future_only)
        {
            printf("  Direction:     Future-only (j > i)\n");
        }
        else
        {
            printf("  Direction:     Bidirectional\n");
        }
    }
    if (config->epsilon > 0.0)
    {
        printf("  ANN Epsilon:   %.4f\n", config->epsilon);
    }
    if (config->use_multi_pivot)
    {
        printf("  Multi-Pivot:   Enabled (AESA/LAESA Indexing)\n");
    }
    if (config->use_reciprocal)
    {
        printf("  Reciprocal:    Enabled (Symmetric d(i,j)=d(j,i))\n");
    }
    if (config->use_angular_bound)
    {
        printf("  Angular Bound: Enabled (Directional Cosine Bounding)\n");
    }
    if (config->use_two_hop)
    {
        printf("  2-Hop Injection: Enabled (seeds=%d, max=%d)\n",
               config->two_hop_seeds, config->two_hop_max_cands);
    }
    if (config->query_data_path != NULL && config->use_trajectory)
    {
        printf("  Trajectory:    Enabled (Sequential Heap & Seed Warm-Start)\n");
    }
    if (config->approx_mode)
    {
        int eff_ef = (config->ef_search > 0) ? config->ef_search : 2 * config->k;
        printf("  Approx Search: Enabled (ef_search = %d)\n", eff_ef);
    }
    else if (config->ef_search > 0)
    {
        printf("  Search Pool:   ef_search = %d\n", config->ef_search);
    }
    if (config->use_rq8)
    {
        printf("  RQ8 Filtering:  Enabled (%s, %s)\n",
               config->rq8_approx ? "Relaxed Approx Mode" : "Exact Lower-Bound Mode",
               config->use_e8_quant ? "E8 Block Lattice" : "Cubic Z^D Lattice");
    }
    if (config->use_e8_graph)
    {
        printf("  E8 Graph:       Enabled (240-NN Gosset Polytope Routing)\n");
    }
    else if (config->use_sq16)
    {
        printf("  SQ16 Filtering: Enabled (%s)\n",
               config->sq16_approx ? "Relaxed Approx Mode" : "Exact Lower-Bound Mode");
    }
    else if (config->use_sq8)
    {
        printf("  SQ8 Filtering:  Enabled (%s)\n",
               config->sq8_approx ? "Relaxed Approx Mode" : "Exact Lower-Bound Mode");
    }
    printf("  Precision:     %s\n",
           config->use_double ? "64-bit Double Precision" : "32-bit Single Precision (Default)");
    if (config->use_gpu)
    {
        if (config->gpu_batch_size > 0)
        {
            printf("  Acceleration:  CUDA GPU (Device %d, Batch Size %d)\n",
                   config->gpu_device_id, config->gpu_batch_size);
        }
        else
        {
            printf("  Acceleration:  CUDA GPU (Device %d, Batch Size Auto)\n",
                   config->gpu_device_id);
        }
    }
    printf("\n");
}
