#!/usr/bin/env python3
"""
Generate C source file containing embedded recipes and suite catalog for gric-mcp.
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from c_embed import escape_c_string

def parse_markdown_with_frontmatter(fpath):
    with open(fpath, "r", encoding="utf-8") as f:
        text = f.read()

    name = None
    title = None
    body = text

    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            fm = parts[1].strip()
            body = parts[2].lstrip()
            for line in fm.split("\n"):
                if ":" in line:
                    key, val = line.split(":", 1)
                    key = key.strip()
                    val = val.strip().strip('"').strip("'")
                    if key == "name":
                        name = val
                    elif key == "title":
                        title = val

    if not name:
        name = os.path.splitext(os.path.basename(fpath))[0]
    if not title:
        title = name.replace("_", " ").title()

    return name, title, body

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <docs_dir> <output_c_file>")
        sys.exit(1)

    docs_dir = sys.argv[1]
    output_c = sys.argv[2]

    recipes_dir = os.path.join(docs_dir, "recipes")
    programs_json = os.path.join(docs_dir, "suite", "programs.json")

    recipes = []
    if os.path.isdir(recipes_dir):
        files = sorted([f for f in os.listdir(recipes_dir) if f.endswith(".md")])
        for f in files:
            p = os.path.join(recipes_dir, f)
            name, title, body = parse_markdown_with_frontmatter(p)
            recipes.append({
                "name": name,
                "title": title,
                "body": body,
                "var_name": "recipe_body_" + re.sub(r'[^a-zA-Z0-9_]', '_', name)
            })

    programs = []
    if os.path.isfile(programs_json):
        with open(programs_json, "r", encoding="utf-8") as f:
            programs = json.load(f)

    # Generate C file
    c_lines = [
        "/**",
        " * @file mcp_content_gen.c",
        " * @brief Auto-generated embedded recipes and suite catalog database.",
        " *",
        " * DO NOT EDIT MANUALLY. Generated by tools/gen_mcp_content.py",
        " */",
        "",
        '#include "mcp_content.h"',
        "#include <string.h>",
        "",
    ]

    # Emit recipe body constants
    for r in recipes:
        c_lines.append(f'static const char {r["var_name"]}[] =')
        c_lines.append(escape_c_string(r["body"]) + ";")
        c_lines.append("")

    # Emit recipes table
    c_lines.append("static const struct mcp_recipe s_recipes[] = {")
    for r in recipes:
        name_esc = r["name"].replace('"', '\\"')
        title_esc = r["title"].replace('"', '\\"')
        c_lines.append(f'    {{ "{name_esc}", "{title_esc}", {r["var_name"]} }},')
    c_lines.append("};")
    c_lines.append("")

    # Emit suite programs table
    c_lines.append("static const struct mcp_suite_program s_suite_programs[] = {")
    for p in programs:
        def c_str(val):
            if val is None:
                return "NULL"
            esc = str(val).replace("\\", "\\\\").replace('"', '\\"')
            return f'"{esc}"'

        c_lines.append("    {")
        c_lines.append(f'        .name     = {c_str(p.get("name"))},')
        c_lines.append(f'        .category = {c_str(p.get("category"))},')
        c_lines.append(f'        .summary  = {c_str(p.get("summary"))},')
        c_lines.append(f'        .usage    = {c_str(p.get("usage"))},')
        c_lines.append(f'        .requires = {c_str(p.get("requires"))},')
        c_lines.append(f'        .alias_of = {c_str(p.get("alias_of"))},')
        c_lines.append("    },")
    c_lines.append("};")
    c_lines.append("")

    # Accessors
    c_lines.extend([
        "const struct mcp_recipe *mcp_recipe_table(",
        "    size_t *count)",
        "{",
        "    if (count != NULL)",
        "    {",
        "        *count = sizeof(s_recipes) / sizeof(s_recipes[0]);",
        "    }",
        "    return s_recipes;",
        "} // mcp_recipe_table",
        "",
        "const struct mcp_recipe *mcp_recipe_find(",
        "    const char *name)",
        "{",
        "    if (name == NULL)",
        "    {",
        "        return NULL;",
        "    }",
        "    size_t count = sizeof(s_recipes) / sizeof(s_recipes[0]);",
        "    for (size_t ii = 0; ii < count; ii++)",
        "    {",
        "        if (strcmp(s_recipes[ii].name, name) == 0)",
        "        {",
        "            return &s_recipes[ii];",
        "        }",
        "    }",
        "    return NULL;",
        "} // mcp_recipe_find",
        "",
        "const struct mcp_suite_program *mcp_suite_program_table(",
        "    size_t *count)",
        "{",
        "    if (count != NULL)",
        "    {",
        "        *count = sizeof(s_suite_programs) / sizeof(s_suite_programs[0]);",
        "    }",
        "    return s_suite_programs;",
        "} // mcp_suite_program_table",
        ""
    ])

    out_dir = os.path.dirname(output_c)
    if out_dir and not os.path.exists(out_dir):
        os.makedirs(out_dir, exist_ok=True)

    with open(output_c, "w", encoding="utf-8") as f:
        f.write("\n".join(c_lines))

    print(f"Generated {output_c} with {len(recipes)} recipes and {len(programs)} suite programs.")

if __name__ == "__main__":
    main()
