#!/usr/bin/env python3
"""
Generate C source file containing compile-time embedded Markdown help topics.
"""

import os
import sys
import re

ALIASES = {
    "pred": ["predf"],
    "jtf": ["pass2"],
    "no_xtile": ["no_pass2"],
    "shm": ["shm-file"],
    "algorithm": ["algorithms"],
    "performance": ["tuning"],
    "compression": ["statespace"],
    "pass2nearest": ["reassign", "second_pass", "pass2_nearest", "no_pass2nearest", "no_reassign"],
    "evals": ["trace", "no_evals"],
    "verbose": ["veryverbose"],
    "entropy_leader": ["entropy_leader_cutoff"],
}

def escape_c_string(text):
    """Escape text for inclusion in C string literal with line wrapping < 90 chars."""
    lines = text.split("\n")
    escaped_lines = []
    for line in lines:
        # Wrap each line into ~70 char raw segments before escaping
        chunk_size = 65
        for i in range(0, max(len(line), 1), chunk_size):
            chunk = line[i:i + chunk_size]
            # If this is the last chunk of the line, append \n
            if i + chunk_size >= len(line):
                chunk += "\n"
            esc = chunk.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            escaped_lines.append(f'    "{esc}"')
    return "\n".join(escaped_lines)

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <docs/help_dir> <output_c_file>")
        sys.exit(1)

    help_dir = sys.argv[1]
    output_c = sys.argv[2]

    if not os.path.isdir(help_dir):
        print(f"Error: {help_dir} is not a directory")
        sys.exit(1)

    topics = []
    
    # Sort files for deterministic build output
    files = sorted(os.listdir(help_dir))
    for fname in files:
        if not fname.endswith(".md"):
            continue
        
        fpath = os.path.join(help_dir, fname)
        with open(fpath, "r", encoding="utf-8") as f:
            content = f.read().strip()
        
        # Determine keyword from first line '# <keyword>' or filename
        first_line = content.split("\n")[0] if content else ""
        if first_line.startswith("# "):
            keyword = first_line[2:].strip()
        else:
            keyword = fname[:-3].replace("_", "/")
        
        var_name = "topic_" + re.sub(r'[^a-zA-Z0-9_]', '_', keyword)
        topics.append({
            "keyword": keyword,
            "var_name": var_name,
            "content": content,
            "filename": fname
        })

    # Generate C code
    c_lines = [
        "/**",
        " * @file help_topics_gen.c",
        " * @brief Auto-generated embedded Markdown help topics database.",
        " *",
        " * DO NOT EDIT MANUALLY. Generated by tools/gen_help_c.py from docs/help/",
        " */",
        "",
        "#include <string.h>",
        "#include <stddef.h>",
        "",
        "struct HelpTopicEntry",
        "{",
        "    const char *keyword;",
        "    const char *content;",
        "};",
        "",
    ]

    for t in topics:
        c_lines.append(f"static const char {t['var_name']}[] =")
        c_lines.append(escape_c_string(t['content']) + ";")
        c_lines.append("")

    c_lines.append("static const struct HelpTopicEntry help_topic_table[] = {")
    
    for t in topics:
        c_lines.append(f'    {{"{t["keyword"]}", {t["var_name"]}}},')
        # Add aliases if any
        if t["keyword"] in ALIASES:
            for alias in ALIASES[t["keyword"]]:
                c_lines.append(f'    {{"{alias}", {t["var_name"]}}},')
    
    c_lines.append("    {NULL, NULL}")
    c_lines.append("};")
    c_lines.append("")
    
    c_lines.append("const char *help_topic_lookup(")
    c_lines.append("    const char *keyword)")
    c_lines.append("{")
    c_lines.append("    if (keyword == NULL)")
    c_lines.append("    {")
    c_lines.append("        return NULL;")
    c_lines.append("    }")
    c_lines.append("")
    c_lines.append("    for (size_t ii = 0; help_topic_table[ii].keyword != NULL; ii++)")
    c_lines.append("    {")
    c_lines.append("        if (strcmp(help_topic_table[ii].keyword, keyword) == 0)")
    c_lines.append("        {")
    c_lines.append("            return help_topic_table[ii].content;")
    c_lines.append("        }")
    c_lines.append("    }")
    c_lines.append("")
    c_lines.append("    return NULL;")
    c_lines.append("}")
    c_lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(output_c)), exist_ok=True)
    with open(output_c, "w", encoding="utf-8") as f:
        f.write("\n".join(c_lines))

    print(f"Generated {output_c} with {len(topics)} topics.")

if __name__ == "__main__":
    main()
