/**
 * @file knn_cli.c
 * @brief Command-line interface parser and help renderer for gric-knn.
 */

#define _POSIX_C_SOURCE 200809L
#include "knn_cli.h"
#include "shared/cli_colors.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <string.h>
#include <time.h>

void knn_cli_print_usage(
    const char *progname)
{
    fprintf(stderr, "Usage: %s <input_data> <cluster_dir> [options]\n", progname);
}

void knn_cli_print_help(
    const char *progname)
{
    printf("%sNAME%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %sgric-knn%s - Out-of-core metric-pruned k-nearest neighbors solver\n\n",
           ansi_bold_green, ansi_reset);

    printf("%sUSAGE%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %s%s%s %s<input_data>%s %s<cluster_dir>%s %s[options]%s\n\n",
           ansi_bold_green, progname, ansi_reset,
           ansi_color_magenta, ansi_reset,
           ansi_color_magenta, ansi_reset,
           ansi_color_grey, ansi_reset);

    printf("%sDESCRIPTION%s\n", ansi_bold_cyan, ansi_reset);
    printf("  Identifies the k-nearest neighbors for each frame in a dataset using\n");
    printf("  the cluster anchors and metric distance bounds generated by Pass 1 "
           "(gric-cluster).\n");
    printf("  Maintains a strictly bounded resident RAM footprint while pruning 95-99%%\n");
    printf("  of high-dimensional distance evaluations.\n\n");

    printf("%sOPTIONS%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %s-query%s %s<path>%s         External query dataset (cross-dataset k-NN mode)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-k%s %s<int>%s              Number of nearest neighbors to find "
           "(%sdefault:%s 10)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-o, --output%s %s<path>%s   Output file path "
           "(default: <cluster_dir>/knn_k<K>.[fits|txt])\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-dtmin%s %s<int>%s          Min frame index separation |i - j| >= dtmin "
           "(%sdefault:%s 1)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-past%s                 Search only among preceding frames (j < i)\n",
           ansi_color_green, ansi_reset);
    printf("  %s-future%s               Search only among subsequent frames (j > i)\n",
           ansi_color_green, ansi_reset);
    printf("  %s-eps%s %s<float>%s          (1+eps)-ANN relaxation slack factor "
           "(%sdefault:%s 0.0)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-rlim%s %s<float>%s         Maximum distance cutoff "
           "(ignore neighbors beyond rlim)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s--all-queries%s         Do not refuse out-of-cluster queries (exhaustive)\n",
           ansi_color_green, ansi_reset);
    printf("  %s-nthreads%s %s<int>%s       Number of OpenMP worker threads "
           "(%sdefault:%s all CPU cores)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-fits%s                 Force FITS output format\n",
           ansi_color_green, ansi_reset);
    printf("  %s-txt%s                  Force ASCII text output format\n",
           ansi_color_green, ansi_reset);
    printf("  %s-multipivot%s, %s-multi_pivot%s Enable Multi-Anchor Pivot Bounding (AESA)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-angular%s, %s--angular%s       Enable Angular Cosine Directional Bounding\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-angular%s, %s--no-angular%s Disable Angular Cosine Directional Bounding\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-trajectory%s, %s--trajectory%s   Enable Trajectory Momentum\n"
           "                                (for smooth trajectories)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-trajectory%s             Disable Trajectory Momentum (default)\n",
           ansi_color_green, ansi_reset);
    printf("  %s-no-reciprocal%s         Disable Symmetric Distance Reciprocal Push\n",
           ansi_color_green, ansi_reset);
    printf("  %s-two-hop%s, %s--two-hop%s       Enable 2-Hop Candidate Injection "
           "(%sdefault: on%s)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-no-two-hop%s, %s--no-two-hop%s Disable 2-Hop Candidate Injection\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-two-hop-seeds%s %s<int>%s    Number of top seeds to expand (default: 2)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-two-hop-max%s %s<int>%s      Max 2-hop candidates evaluated per query "
           "(default: 32)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-approx%s, %s--approx%s         Fast Approximate Graph Search "
           "(10-20 evals/query)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-ef-search%s %s<L>%s       Search pool / heap size (default: 2*k in approx)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-progress%s             Display live progress bar\n",
           ansi_color_green, ansi_reset);
    printf("  %s-double%s, %s--double%s         Run computations in 64-bit double precision "
           "(%sdefault:%s float)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-rq8%s, %s--rq8%s               Enable 8-bit residual vector quantization "
           "(%sdefault:%s on)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-no-rq8%s, %s--no-rq8%s         Disable 8-bit residual quantization filtering\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-rq8-save%s %s<path>%s      Save 8-bit residual quantized dataset to sidecar\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-rq8-load%s %s<path>%s      Load 8-bit residual quantized dataset from sidecar\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-rq8-approx%s, %s--rq8-approx%s Enable approximate lower bound in RQ8\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-pq%s, %s--pq%s                 Enable Product Quantization (PQ) FastScan\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-pq%s, %s--no-pq%s           Disable Product Quantization FastScan\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-pq-m%s %s<int>%s               Number of subquantizers (default: dim/4)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-pq-bits%s %s<4|8>%s            PQ codebook bits (default: 4)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-pq-save%s %s<path>%s           Save PQ codebook and codes to sidecar\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-pq-load%s %s<path>%s           Load PQ codebook and codes from sidecar\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-pq-rerank%s %s<int>%s          Top candidates to re-evaluate with exact dist\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-rabitq%s, %s--rabitq%s         Enable Randomized Bit Quantization (RaBitQ)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-rabitq%s, %s--no-rabitq%s   Disable RaBitQ filtering\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-rabitq-bits%s %s<1|2>%s        RaBitQ bit depth (default: 2)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-rabitq-save%s %s<path>%s       Save RaBitQ dataset to sidecar\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-rabitq-load%s %s<path>%s       Load RaBitQ dataset from sidecar\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-rabitq-approx%s                Enable approximate lower bound in RaBitQ\n",
           ansi_color_green, ansi_reset);
    printf("  %s-sq8%s, %s--sq8%s               Enable 8-bit scalar quantization filtering\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-sq8%s, %s--no-sq8%s         Disable 8-bit scalar quantization filtering\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-sq8-save%s %s<path>%s      Save quantized dataset to sidecar file\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-sq8-load%s %s<path>%s      Load quantized dataset from sidecar file\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-sq16%s, %s--sq16%s             Enable 16-bit scalar quantization filtering\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-sq16%s, %s--no-sq16%s       Disable 16-bit scalar quantization filtering\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-sq16-save%s %s<path>%s     Save 16-bit quantized dataset to sidecar file\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-sq16-load%s %s<path>%s     Load 16-bit quantized dataset from sidecar file\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-sq16-ratio%s %s<alpha>%s   Max quantization step ratio alpha "
           "(%sdefault:%s 0.05)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-sq16-sparse%s, %s--sq16-sparse%s Enable SQ16 SparseCache Direct SIMD\n"
           "                                (0 MB resident transposed index)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-sq16-sparse-lru%s            Enable 16-block LRU Transposed FastScan\n"
           "                                (512 KB per thread in L2 cache)\n",
           ansi_color_green, ansi_reset);
    printf("  %s-memo%s, %s--memo%s             Enable quantized memoization cache\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-memo%s, %s--no-memo%s       Disable quantized memoization cache\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-batch-dist%s          Disable multi-vector SIMD batch distance\n",
           ansi_color_green, ansi_reset);
    printf("  %s-cluster-graph%s, %s--cluster-graph%s Enable Graph-Guided Cluster Routing "
           "(%sdefault:%s on)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-no-cluster-graph%s, %s--no-cluster-graph%s Disable Graph-Guided Routing\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-ef-cluster%s %s<int>%s       Max clusters to evaluate in graph routing "
           "(%sdefault:%s 60)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-prof%s %s<path>%s          Explicit dataset profile file (.gricprof)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-no-prof%s, %s--no-prof%s       Disable auto-loading of .gricprof file\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-mutual%s, %s--no-mutual%s   Disable knn_mutual_dists.bin calculation/output\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-txt%s, %s--no-txt%s         Disable ASCII knn_results.txt output\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-gpu%s, %s--gpu%s               Enable CUDA GPU acceleration\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-gpu-batch-size%s %s<size>%s    Micro-batch size for GPU queries (default: auto)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-gpu-micro-batch%s %s[size]%s   Alias for -gpu-batch-size\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-cpu%s, %s--cpu%s               Force CPU execution (disable GPU)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-gpu-device%s %s<id>%s          Select GPU device ID (default: 0)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-gpu-nprobe%s %s<int>%s         Max clusters to probe on GPU (default: adaptive)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-gpu-bf%s, %s--gpu-brute-force%s Force dense GEMM brute-force on GPU\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-v, -vv%s               Verbosity level\n",
           ansi_color_green, ansi_reset);
    printf("  %s-h, --help%s            Show this help message\n\n",
           ansi_color_green, ansi_reset);

    printf("%sEXAMPLES%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %s$%s %s%s%s dataset.fits cluster_out/ -k 10 -dtmin 5\n",
           ansi_color_grey, ansi_reset, ansi_bold_green, progname, ansi_reset);
    printf("  %s$%s %s%s%s spiral.txt cluster_out/ -k 20 -eps 0.05 -progress\n",
           ansi_color_grey, ansi_reset, ansi_bold_green, progname, ansi_reset);
    printf("  %s$%s %s%s%s train_A.txt cluster_out/ -query test_C.txt -k 10\n\n",
           ansi_color_grey, ansi_reset, ansi_bold_green, progname, ansi_reset);
    cli_print_color_mode();
}

/**
 * knn_cli_set_defaults() - Initialize KnnConfig with default parameter values.
 * @config: Pointer to KnnConfig to initialize.
 */
static void knn_cli_set_defaults(
    KnnConfig *config)
{
    memset(config, 0, sizeof(KnnConfig));
    config->k = 50;
    config->min_temporal_sep = 1;   // Exclude self-matching by default
    config->output_format = KNN_FORMAT_AUTO;
    config->progress_mode = 0;
    config->verbose_level = 1;
    config->use_reciprocal = 1;     // Enabled by default for bidirectional search
    config->use_multi_pivot = 1;    // Enabled by default for multi-anchor pivot bounding
    config->use_angular_bound = 1;  // Enabled by default for directional pruning
    config->use_trajectory = 0;     // Disabled by default; enable for smooth trajectories
    config->use_rq8 = 1;            // Enabled by default for 8-bit residual quantization
    config->use_sq8 = 0;            // Fallback scalar quantization
    config->use_sq16 = 0;
    config->use_sq16_sparse = 0;    // On-demand FastScan block transpose
    config->use_sq16_sparse_lru = 0; // 16-block LRU Transposed FastScan
    config->use_rabitq = 0;         // RaBitQ randomized bit quantization (optional)
    config->rabitq_bits = 2;        // Default 2-bit Extended RaBitQ
    config->use_dcc_sq16 = 1;       // Enabled by default for 16-bit quantized DCC matrix
    config->sq16_ratio = 0.05;      // Enforce sqrt(D)*scale <= alpha*rlim
    config->use_memo = 1;           // Enabled by default for quantized memoization
    config->use_batch_dist = 1;     // Enabled by default for multi-vector SIMD batching
    config->use_cluster_graph = 1;  // Enabled by default for graph-guided cluster routing
    config->ef_cluster = 0;         // 0 = dynamic auto-scaled cluster budget
    config->use_two_hop = 1;        // Enabled by default for 2-hop candidate injection
    config->two_hop_seeds = 2;      // Expand top 2 closest seeds
    config->two_hop_max_cands = 32; // Maximum 2-hop candidate evaluations per query
    config->no_txt = 1;             // Binary output by default (.bin); use -txt for text output
}

/**
 * knn_cli_parse_io_opt() - Parse I/O, format, execution, and profiling options.
 * @argc:      Total argument count.
 * @argv:      Argument strings array.
 * @arg_idx:   Pointer to current argument index.
 * @config:    Pointer to KnnConfig.
 * @k_set:     Flag indicating -k was explicitly passed.
 * @dtmin_set: Flag indicating -dtmin was explicitly passed.
 *
 * Return: 1 if option was recognized, 0 if not, -1 on error.
 */
static int knn_cli_parse_io_opt(
    int        argc,
    char     **argv,
    int       *arg_idx,
    KnnConfig *config,
    int       *k_set,
    int       *dtmin_set)
{
    int i = *arg_idx;

    if (strcmp(argv[i], "-query") == 0 || strcmp(argv[i], "--query") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -query requires a path argument\n");
            return -1;
        }
        config->query_data_path = argv[++(*arg_idx)];
        return 1;
    }
    if (strcmp(argv[i], "-k") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -k requires an integer argument\n");
            return -1;
        }
        config->k = atoi(argv[++(*arg_idx)]);
        *k_set = 1;
        return 1;
    }
    if (strcmp(argv[i], "-o") == 0 || strcmp(argv[i], "--output") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -o requires a path argument\n");
            return -1;
        }
        config->output_path = argv[++(*arg_idx)];
        char *ext = strrchr(config->output_path, '.');
        if (ext != NULL && strcmp(ext, ".txt") == 0)
        {
            config->output_format = KNN_FORMAT_TXT;
            config->no_txt = 0;
        }
        return 1;
    }
    if (strcmp(argv[i], "-dtmin") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -dtmin requires an integer argument\n");
            return -1;
        }
        config->min_temporal_sep = atoi(argv[++(*arg_idx)]);
        *dtmin_set = 1;
        return 1;
    }
    if (strcmp(argv[i], "-past") == 0)
    {
        config->past_only = 1;
        return 1;
    }
    if (strcmp(argv[i], "-future") == 0)
    {
        config->future_only = 1;
        return 1;
    }
    if (strcmp(argv[i], "-eps") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -eps requires a float argument\n");
            return -1;
        }
        config->epsilon = atof(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-rlim") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -rlim requires a float argument\n");
            return -1;
        }
        config->rlim_cutoff = atof(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-all-queries") == 0 || strcmp(argv[i], "--all-queries") == 0)
    {
        config->refuse_unclustered = -1;
        return 1;
    }
    if (strcmp(argv[i], "-nthreads") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -nthreads requires an integer argument\n");
            return -1;
        }
        config->nthreads = atoi(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-fits") == 0)
    {
        config->output_format = KNN_FORMAT_FITS;
        return 1;
    }
    if (strcmp(argv[i], "-txt") == 0 || strcmp(argv[i], "--txt") == 0)
    {
        config->output_format = KNN_FORMAT_TXT;
        config->no_txt = 0;
        return 1;
    }
    if (strcmp(argv[i], "-progress") == 0)
    {
        config->progress_mode = 1;
        return 1;
    }
    if (strcmp(argv[i], "-double") == 0 || strcmp(argv[i], "--double") == 0)
    {
        config->use_double = 1;
        return 1;
    }
    if (strcmp(argv[i], "-prof") == 0 || strcmp(argv[i], "--prof") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -prof requires a filepath argument\n");
            return -1;
        }
        config->prof_filename = argv[++(*arg_idx)];
        return 1;
    }
    if (strcmp(argv[i], "-no-prof") == 0 || strcmp(argv[i], "--no-prof") == 0)
    {
        config->no_prof = 1;
        return 1;
    }
    if (strcmp(argv[i], "-no-mem") == 0 || strcmp(argv[i], "--no-mem") == 0 ||
        strcmp(argv[i], "-no-cache") == 0)
    {
        config->no_cache_dataset = 1;
        return 1;
    }
    if (strcmp(argv[i], "-no-mutual") == 0 || strcmp(argv[i], "--no-mutual") == 0 ||
        strcmp(argv[i], "-no_mutual") == 0 || strcmp(argv[i], "-nomutual") == 0)
    {
        config->no_mutual = 1;
        return 1;
    }
    if (strcmp(argv[i], "-no-txt") == 0 || strcmp(argv[i], "--no-txt") == 0 ||
        strcmp(argv[i], "-no_txt") == 0 || strcmp(argv[i], "-notxt") == 0)
    {
        config->no_txt = 1;
        return 1;
    }
    if (strcmp(argv[i], "-v") == 0)
    {
        config->verbose_level = 2;
        return 1;
    }
    if (strcmp(argv[i], "-vv") == 0)
    {
        config->verbose_level = 3;
        return 1;
    }

    return 0;
}

/**
 * knn_cli_parse_pruning_opt() - Parse pruning heuristics and graph search options.
 * @argc:    Total argument count.
 * @argv:    Argument strings array.
 * @arg_idx: Pointer to current argument index.
 * @config:  Pointer to KnnConfig.
 *
 * Return: 1 if option was recognized, 0 if not, -1 on error.
 */
static int knn_cli_parse_pruning_opt(
    int        argc,
    char     **argv,
    int       *arg_idx,
    KnnConfig *config)
{
    int i = *arg_idx;

    if (strcmp(argv[i], "-multipivot") == 0 || strcmp(argv[i], "--multipivot") == 0 ||
        strcmp(argv[i], "-multi_pivot") == 0 || strcmp(argv[i], "--multi-pivot") == 0)
    {
        config->use_multi_pivot = 1;
        return 1;
    }
    if (strcmp(argv[i], "-no-multipivot") == 0 || strcmp(argv[i], "-no_multipivot") == 0)
    {
        config->use_multi_pivot = 0;
        return 1;
    }
    if (strcmp(argv[i], "-angular") == 0 || strcmp(argv[i], "--angular") == 0 ||
        strcmp(argv[i], "-direction") == 0 || strcmp(argv[i], "--direction") == 0)
    {
        config->use_angular_bound = 1;
        return 1;
    }
    if (strcmp(argv[i], "-no-angular") == 0 || strcmp(argv[i], "--no-angular") == 0 ||
        strcmp(argv[i], "-no-direction") == 0 || strcmp(argv[i], "--no-direction") == 0)
    {
        config->use_angular_bound = 0;
        return 1;
    }
    if (strcmp(argv[i], "-trajectory") == 0 || strcmp(argv[i], "--trajectory") == 0)
    {
        config->use_trajectory = 1;
        return 1;
    }
    if (strcmp(argv[i], "-no-trajectory") == 0 || strcmp(argv[i], "--no-trajectory") == 0 ||
        strcmp(argv[i], "-notrajectory") == 0)
    {
        config->use_trajectory = 0;
        return 1;
    }
    if (strcmp(argv[i], "-reciprocal") == 0 || strcmp(argv[i], "--reciprocal") == 0)
    {
        config->use_reciprocal = 1;
        return 1;
    }
    if (strcmp(argv[i], "-no-reciprocal") == 0 || strcmp(argv[i], "--no-reciprocal") == 0 ||
        strcmp(argv[i], "-noreciprocal") == 0)
    {
        config->use_reciprocal = 0;
        return 1;
    }
    if (strcmp(argv[i], "-approx") == 0 || strcmp(argv[i], "--approx") == 0 ||
        strcmp(argv[i], "-fast") == 0 || strcmp(argv[i], "--fast") == 0)
    {
        config->approx_mode = 1;
        return 1;
    }
    if (strcmp(argv[i], "-ef-search") == 0 || strcmp(argv[i], "--ef-search") == 0 ||
        strcmp(argv[i], "-ef") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -ef-search requires an integer argument\n");
            return -1;
        }
        config->ef_search = atoi(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-cluster-graph") == 0 || strcmp(argv[i], "--cluster-graph") == 0)
    {
        config->use_cluster_graph = 1;
        return 1;
    }
    if (strcmp(argv[i], "-no-cluster-graph") == 0 || strcmp(argv[i], "--no-cluster-graph") == 0)
    {
        config->use_cluster_graph = 0;
        return 1;
    }
    if (strcmp(argv[i], "-ef-cluster") == 0 || strcmp(argv[i], "--ef-cluster") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -ef-cluster requires an integer argument\n");
            return -1;
        }
        config->ef_cluster = atoi(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-two-hop") == 0 || strcmp(argv[i], "--two-hop") == 0)
    {
        config->use_two_hop = 1;
        return 1;
    }
    if (strcmp(argv[i], "-no-two-hop") == 0 || strcmp(argv[i], "--no-two-hop") == 0)
    {
        config->use_two_hop = 0;
        return 1;
    }
    if (strcmp(argv[i], "-two-hop-seeds") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -two-hop-seeds requires an integer argument\n");
            return -1;
        }
        config->two_hop_seeds = atoi(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-two-hop-max") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -two-hop-max requires an integer argument\n");
            return -1;
        }
        config->two_hop_max_cands = atoi(argv[++(*arg_idx)]);
        return 1;
    }

    return 0;
}

/**
 * knn_cli_parse_quant_opt() - Parse quantization algorithms, sidecars, and SIMD memoization.
 * @argc:    Total argument count.
 * @argv:    Argument strings array.
 * @arg_idx: Pointer to current argument index.
 * @config:  Pointer to KnnConfig.
 *
 * Return: 1 if option was recognized, 0 if not, -1 on error.
 */
static int knn_cli_parse_quant_opt(
    int        argc,
    char     **argv,
    int       *arg_idx,
    KnnConfig *config)
{
    int i = *arg_idx;

    if (strcmp(argv[i], "-rq8") == 0 || strcmp(argv[i], "--rq8") == 0)
    {
        config->use_rq8 = 1;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        return 1;
    }
    if (strcmp(argv[i], "-no-rq8") == 0 || strcmp(argv[i], "--no-rq8") == 0 ||
        strcmp(argv[i], "-norq8") == 0)
    {
        config->use_rq8 = 0;
        return 1;
    }
    if (strcmp(argv[i], "-rq8-save") == 0 || strcmp(argv[i], "--rq8-save") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -rq8-save requires a filepath argument\n");
            return -1;
        }
        config->use_rq8 = 1;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        config->rq8_save_path = argv[++(*arg_idx)];
        return 1;
    }
    if (strcmp(argv[i], "-rq8-load") == 0 || strcmp(argv[i], "--rq8-load") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -rq8-load requires a filepath argument\n");
            return -1;
        }
        config->use_rq8 = 1;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        config->rq8_load_path = argv[++(*arg_idx)];
        return 1;
    }
    if (strcmp(argv[i], "-rq8-approx") == 0 || strcmp(argv[i], "--rq8-approx") == 0)
    {
        config->use_rq8 = 1;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        config->use_pq = 0;
        config->rq8_approx = 1;
        return 1;
    }
    if (strcmp(argv[i], "-pq") == 0 || strcmp(argv[i], "--pq") == 0)
    {
        config->use_pq = 1;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        return 1;
    }
    if (strcmp(argv[i], "-no-pq") == 0 || strcmp(argv[i], "--no-pq") == 0 ||
        strcmp(argv[i], "-nopq") == 0)
    {
        config->use_pq = 0;
        return 1;
    }
    if (strcmp(argv[i], "-pq-m") == 0 || strcmp(argv[i], "--pq-m") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -pq-m requires an integer argument\n");
            return -1;
        }
        config->use_pq = 1;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        config->pq_m = atoi(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-pq-bits") == 0 || strcmp(argv[i], "--pq-bits") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -pq-bits requires an integer argument (4 or 8)\n");
            return -1;
        }
        config->use_pq = 1;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        config->pq_bits = atoi(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-pq-save") == 0 || strcmp(argv[i], "--pq-save") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -pq-save requires a filepath argument\n");
            return -1;
        }
        config->use_pq = 1;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        config->pq_save_path = argv[++(*arg_idx)];
        return 1;
    }
    if (strcmp(argv[i], "-pq-load") == 0 || strcmp(argv[i], "--pq-load") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -pq-load requires a filepath argument\n");
            return -1;
        }
        config->use_pq = 1;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        config->pq_load_path = argv[++(*arg_idx)];
        return 1;
    }
    if (strcmp(argv[i], "-pq-rerank") == 0 || strcmp(argv[i], "--pq-rerank") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -pq-rerank requires an integer argument\n");
            return -1;
        }
        config->use_pq = 1;
        config->pq_rerank = atoi(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-rabitq") == 0 || strcmp(argv[i], "--rabitq") == 0)
    {
        config->use_rabitq = 1;
        config->use_pq = 0;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        return 1;
    }
    if (strcmp(argv[i], "-no-rabitq") == 0 || strcmp(argv[i], "--no-rabitq") == 0 ||
        strcmp(argv[i], "-norabitq") == 0)
    {
        config->use_rabitq = 0;
        return 1;
    }
    if (strcmp(argv[i], "-rabitq-bits") == 0 || strcmp(argv[i], "--rabitq-bits") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -rabitq-bits requires an integer argument (1 or 2)\n");
            return -1;
        }
        config->use_rabitq = 1;
        config->use_pq = 0;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        config->rabitq_bits = atoi(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-rabitq-save") == 0 || strcmp(argv[i], "--rabitq-save") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -rabitq-save requires a filepath argument\n");
            return -1;
        }
        config->use_rabitq = 1;
        config->use_pq = 0;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        config->rabitq_save_path = argv[++(*arg_idx)];
        return 1;
    }
    if (strcmp(argv[i], "-rabitq-load") == 0 || strcmp(argv[i], "--rabitq-load") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -rabitq-load requires a filepath argument\n");
            return -1;
        }
        config->use_rabitq = 1;
        config->use_pq = 0;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        config->rabitq_load_path = argv[++(*arg_idx)];
        return 1;
    }
    if (strcmp(argv[i], "-rabitq-approx") == 0 || strcmp(argv[i], "--rabitq-approx") == 0)
    {
        config->use_rabitq = 1;
        config->use_pq = 0;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->use_sq8 = 0;
        config->rabitq_approx = 1;
        return 1;
    }
    if (strcmp(argv[i], "-sq8") == 0 || strcmp(argv[i], "--sq8") == 0)
    {
        config->use_sq8 = 1;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        return 1;
    }
    if (strcmp(argv[i], "-no-sq8") == 0 || strcmp(argv[i], "--no-sq8") == 0 ||
        strcmp(argv[i], "-nosq8") == 0)
    {
        config->use_sq8 = 0;
        return 1;
    }
    if (strcmp(argv[i], "-sq8-save") == 0 || strcmp(argv[i], "--sq8-save") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -sq8-save requires a filepath argument\n");
            return -1;
        }
        config->use_sq8 = 1;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->sq8_save_path = argv[++(*arg_idx)];
        return 1;
    }
    if (strcmp(argv[i], "-sq8-load") == 0 || strcmp(argv[i], "--sq8-load") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -sq8-load requires a filepath argument\n");
            return -1;
        }
        config->use_sq8 = 1;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->sq8_load_path = argv[++(*arg_idx)];
        return 1;
    }
    if (strcmp(argv[i], "-sq8-approx") == 0 || strcmp(argv[i], "--sq8-approx") == 0)
    {
        config->use_sq8 = 1;
        config->use_rq8 = 0;
        config->use_sq16 = 0;
        config->sq8_approx = 1;
        return 1;
    }
    if (strcmp(argv[i], "-sq16") == 0 || strcmp(argv[i], "--sq16") == 0)
    {
        config->use_sq16 = 1;
        config->use_rq8 = 0;
        config->use_sq8 = 0;
        return 1;
    }
    if (strcmp(argv[i], "-no-sq16") == 0 || strcmp(argv[i], "--no-sq16") == 0 ||
        strcmp(argv[i], "-nosq16") == 0)
    {
        config->use_sq16 = 0;
        return 1;
    }
    if (strcmp(argv[i], "-sq16-save") == 0 || strcmp(argv[i], "--sq16-save") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -sq16-save requires a filepath argument\n");
            return -1;
        }
        config->use_sq16 = 1;
        config->use_rq8 = 0;
        config->use_sq8 = 0;
        config->sq16_save_path = argv[++(*arg_idx)];
        return 1;
    }
    if (strcmp(argv[i], "-sq16-load") == 0 || strcmp(argv[i], "--sq16-load") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -sq16-load requires a filepath argument\n");
            return -1;
        }
        config->use_sq16 = 1;
        config->use_rq8 = 0;
        config->use_sq8 = 0;
        config->sq16_load_path = argv[++(*arg_idx)];
        return 1;
    }
    if (strcmp(argv[i], "-sq16-approx") == 0 || strcmp(argv[i], "--sq16-approx") == 0)
    {
        config->use_sq16 = 1;
        config->use_rq8 = 0;
        config->use_sq8 = 0;
        config->sq16_approx = 1;
        return 1;
    }
    if (strcmp(argv[i], "-sq16-ratio") == 0 || strcmp(argv[i], "--sq16-ratio") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -sq16-ratio requires a float argument\n");
            return -1;
        }
        config->sq16_ratio = atof(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-sq16-sparse") == 0 || strcmp(argv[i], "--sq16-sparse") == 0)
    {
        config->use_sq16 = 1;
        config->use_rq8 = 0;
        config->use_sq8 = 0;
        config->use_sq16_sparse = 1;
        return 1;
    }
    if (strcmp(argv[i], "-sq16-sparse-lru") == 0 || strcmp(argv[i], "--sq16-sparse-lru") == 0)
    {
        config->use_sq16 = 1;
        config->use_rq8 = 0;
        config->use_sq8 = 0;
        config->use_sq16_sparse = 1;
        config->use_sq16_sparse_lru = 1;
        return 1;
    }
    if (strcmp(argv[i], "-dcc-sq16") == 0 || strcmp(argv[i], "--dcc-sq16") == 0)
    {
        config->use_dcc_sq16 = 1;
        return 1;
    }
    if (strcmp(argv[i], "-no-dcc-sq16") == 0 || strcmp(argv[i], "--no-dcc-sq16") == 0)
    {
        config->use_dcc_sq16 = 0;
        return 1;
    }
    if (strcmp(argv[i], "-memo") == 0 || strcmp(argv[i], "--memo") == 0)
    {
        config->use_memo = 1;
        return 1;
    }
    if (strcmp(argv[i], "-no-memo") == 0 || strcmp(argv[i], "--no-memo") == 0 ||
        strcmp(argv[i], "-nomemo") == 0)
    {
        config->use_memo = 0;
        return 1;
    }
    if (strcmp(argv[i], "-batch-dist") == 0 || strcmp(argv[i], "--batch-dist") == 0 ||
        strcmp(argv[i], "-batchdist") == 0)
    {
        config->use_batch_dist = 1;
        return 1;
    }
    if (strcmp(argv[i], "-no-batch-dist") == 0 || strcmp(argv[i], "--no-batch-dist") == 0 ||
        strcmp(argv[i], "-nobatchdist") == 0)
    {
        config->use_batch_dist = 0;
        return 1;
    }

    return 0;
}

/**
 * knn_cli_parse_gpu_opt() - Parse CUDA and GPU acceleration options.
 * @argc:    Total argument count.
 * @argv:    Argument strings array.
 * @arg_idx: Pointer to current argument index.
 * @config:  Pointer to KnnConfig.
 *
 * Return: 1 if option was recognized, 0 if not, -1 on error.
 */
static int knn_cli_parse_gpu_opt(
    int        argc,
    char     **argv,
    int       *arg_idx,
    KnnConfig *config)
{
    int i = *arg_idx;

    if (strcmp(argv[i], "-gpu") == 0 || strcmp(argv[i], "--gpu") == 0)
    {
        config->use_gpu = 1;
        return 1;
    }
    if (strcmp(argv[i], "-cpu") == 0 || strcmp(argv[i], "--cpu") == 0)
    {
        config->use_gpu = 0;
        return 1;
    }
    if (strcmp(argv[i], "-gpu-device") == 0 || strcmp(argv[i], "--gpu-device") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: --gpu-device requires an integer argument\n");
            return -1;
        }
        config->use_gpu = 1;
        config->gpu_device_id = atoi(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-gpu-batch-size") == 0 || strcmp(argv[i], "--gpu-batch-size") == 0 ||
        strcmp(argv[i], "-gpu-micro-batch") == 0 || strcmp(argv[i], "--gpu-micro-batch") == 0)
    {
        config->use_gpu = 1;
        if (i + 1 < argc && argv[i + 1][0] != '-')
        {
            config->gpu_batch_size = atoi(argv[++(*arg_idx)]);
        }
        else
        {
            config->gpu_batch_size = 64;
        }
        return 1;
    }
    if (strcmp(argv[i], "-gpu-nprobe") == 0 || strcmp(argv[i], "--gpu-nprobe") == 0 ||
        strcmp(argv[i], "-nprobe") == 0)
    {
        if (i + 1 >= argc)
        {
            fprintf(stderr, "Error: -gpu-nprobe requires an integer argument\n");
            return -1;
        }
        config->use_gpu = 1;
        config->gpu_nprobe = atoi(argv[++(*arg_idx)]);
        return 1;
    }
    if (strcmp(argv[i], "-gpu-bf") == 0 || strcmp(argv[i], "--gpu-bf") == 0 ||
        strcmp(argv[i], "-gpu-brute-force") == 0 || strcmp(argv[i], "--gpu-brute-force") == 0)
    {
        config->use_gpu = 1;
        config->use_gpu_bruteforce = 1;
        return 1;
    }

    return 0;
}

/**
 * knn_cli_parse_positional() - Assign non-option positional arguments to KnnConfig.
 * @arg:      Positional argument string.
 * @config:   Pointer to KnnConfig.
 * @progname: Name of the program for error output.
 *
 * Return: 0 on success, 1 on error.
 */
static int knn_cli_parse_positional(
    char       *arg,
    KnnConfig  *config,
    const char *progname)
{
    if (config->input_data_path == NULL)
    {
        config->input_data_path = arg;
    }
    else if (config->cluster_dir == NULL)
    {
        config->cluster_dir = arg;
    }
    else
    {
        fprintf(stderr, "Error: Too many positional arguments\n");
        knn_cli_print_usage(progname);
        return 1;
    }
    return 0;
}

/**
 * knn_cli_validate() - Validate consistency of parsed parameters and apply mode adjustments.
 * @config:    Pointer to KnnConfig to validate.
 * @progname:  Name of the program for error output.
 * @k_set:     Flag indicating -k was explicitly passed.
 * @dtmin_set: Flag indicating -dtmin was explicitly passed.
 *
 * Return: 0 on success, 1 on validation error.
 */
static int knn_cli_validate(
    KnnConfig  *config,
    const char *progname,
    int         k_set,
    int         dtmin_set)
{
    if (config->input_data_path == NULL || config->cluster_dir == NULL)
    {
        fprintf(stderr, "Error: Missing required arguments <input_data> and <cluster_dir>\n");
        knn_cli_print_usage(progname);
        return 1;
    }

    if (config->k <= 0)
    {
        fprintf(stderr, "Error: k must be >= 1\n");
        return 1;
    }

    if (config->query_data_path != NULL)
    {
        if (!k_set)
        {
            config->k = 30; // Default k=30 for cross-dataset query mode
        }
        if (!dtmin_set)
        {
            config->min_temporal_sep = 0; // Cross-dataset query has no temporal self-exclusion
        }
        config->use_reciprocal = 0;
    }

    if (config->past_only || config->future_only)
    {
        config->use_reciprocal = 0;
    }

    return 0;
}

int knn_cli_parse(
    int        argc,
    char     **argv,
    KnnConfig *config)
{
    if (config == NULL)
    {
        return 1;
    }

    knn_cli_set_defaults(config);

    int k_explicitly_set = 0;
    int dtmin_explicitly_set = 0;
    int arg_idx = 1;

    while (arg_idx < argc)
    {
        if (strcmp(argv[arg_idx], "-h") == 0 || strcmp(argv[arg_idx], "--help") == 0)
        {
            knn_cli_print_help(argv[0]);
            return 2;
        }

        int res = knn_cli_parse_io_opt(argc, argv, &arg_idx, config,
                                       &k_explicitly_set, &dtmin_explicitly_set);
        if (res < 0)
        {
            return 1;
        }
        if (res > 0)
        {
            arg_idx++;
            continue;
        }

        res = knn_cli_parse_pruning_opt(argc, argv, &arg_idx, config);
        if (res < 0)
        {
            return 1;
        }
        if (res > 0)
        {
            arg_idx++;
            continue;
        }

        res = knn_cli_parse_quant_opt(argc, argv, &arg_idx, config);
        if (res < 0)
        {
            return 1;
        }
        if (res > 0)
        {
            arg_idx++;
            continue;
        }

        res = knn_cli_parse_gpu_opt(argc, argv, &arg_idx, config);
        if (res < 0)
        {
            return 1;
        }
        if (res > 0)
        {
            arg_idx++;
            continue;
        }

        if (argv[arg_idx][0] == '-')
        {
            fprintf(stderr, "Error: Unknown option '%s'\n", argv[arg_idx]);
            knn_cli_print_usage(argv[0]);
            return 1;
        }

        if (knn_cli_parse_positional(argv[arg_idx], config, argv[0]) != 0)
        {
            return 1;
        }
        arg_idx++;
    } // while (arg_idx < argc)

    return knn_cli_validate(config, argv[0], k_explicitly_set, dtmin_explicitly_set);
}

void knn_cli_print_banner(
    const KnnConfig *config)
{
    printf("%sStarting gric-knn: Out-of-Core Metric-Pruned k-NN Solver%s\n",
           ansi_bold_green, ansi_reset);
    printf("  Dataset (A):   %s\n", config->input_data_path);
    printf("  Cluster Dir:   %s\n", config->cluster_dir);
    if (config->query_data_path != NULL)
    {
        printf("  Query Set (C): %s (Cross-Dataset Mode)\n", config->query_data_path);
    }
    printf("  k Neighbors:   %d\n", config->k);
    if (config->query_data_path == NULL)
    {
        printf("  Min Temp Sep:  %d frames\n", config->min_temporal_sep);
        if (config->past_only)
        {
            printf("  Direction:     Past-only (j < i)\n");
        }
        else if (config->future_only)
        {
            printf("  Direction:     Future-only (j > i)\n");
        }
        else
        {
            printf("  Direction:     Bidirectional\n");
        }
    }
    if (config->epsilon > 0.0)
    {
        printf("  ANN Epsilon:   %.4f\n", config->epsilon);
    }
    if (config->use_multi_pivot)
    {
        printf("  Multi-Pivot:   Enabled (AESA/LAESA Indexing)\n");
    }
    if (config->use_reciprocal)
    {
        printf("  Reciprocal:    Enabled (Symmetric d(i,j)=d(j,i))\n");
    }
    if (config->use_angular_bound)
    {
        printf("  Angular Bound: Enabled (Directional Cosine Bounding)\n");
    }
    if (config->use_two_hop)
    {
        printf("  2-Hop Injection: Enabled (seeds=%d, max=%d)\n",
               config->two_hop_seeds, config->two_hop_max_cands);
    }
    if (config->query_data_path != NULL && config->use_trajectory)
    {
        printf("  Trajectory:    Enabled (Sequential Heap & Seed Warm-Start)\n");
    }
    if (config->approx_mode)
    {
        int eff_ef = (config->ef_search > 0) ? config->ef_search : 2 * config->k;
        printf("  Approx Search: Enabled (ef_search = %d)\n", eff_ef);
    }
    else if (config->ef_search > 0)
    {
        printf("  Search Pool:   ef_search = %d\n", config->ef_search);
    }
    if (config->use_rq8)
    {
        printf("  RQ8 Filtering:  Enabled (%s)\n",
               config->rq8_approx ? "Relaxed Approx Mode" : "Exact Lower-Bound Mode");
    }
    else if (config->use_sq16)
    {
        printf("  SQ16 Filtering: Enabled (%s)\n",
               config->sq16_approx ? "Relaxed Approx Mode" : "Exact Lower-Bound Mode");
    }
    else if (config->use_sq8)
    {
        printf("  SQ8 Filtering:  Enabled (%s)\n",
               config->sq8_approx ? "Relaxed Approx Mode" : "Exact Lower-Bound Mode");
    }
    printf("  Precision:     %s\n",
           config->use_double ? "64-bit Double Precision" : "32-bit Single Precision (Default)");
    if (config->use_gpu)
    {
        if (config->gpu_batch_size > 0)
        {
            printf("  Acceleration:  CUDA GPU (Device %d, Batch Size %d)\n",
                   config->gpu_device_id, config->gpu_batch_size);
        }
        else
        {
            printf("  Acceleration:  CUDA GPU (Device %d, Batch Size Auto)\n",
                   config->gpu_device_id);
        }
    }
    printf("\n");

}
