/**
 * @file main.c
 * @brief Entry point for gric-knn: Out-of-Core Metric-Pruned k-NN Solver.
 */

#define _POSIX_C_SOURCE 200809L
#include "knn_defs.h"
#include "knn_engine.h"
#include "knn_loader.h"
#include "knn_writer.h"
#include "shared/cli_colors.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

static void print_usage(
    const char *progname)
{
    fprintf(stderr, "Usage: %s <input_data> <cluster_dir> [options]\n", progname);
}

static void print_help(
    const char *progname)
{
    printf("%sNAME%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %sgric-knn%s - Out-of-core metric-pruned k-nearest neighbors solver\n\n",
           ansi_bold_green, ansi_reset);

    printf("%sUSAGE%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %s%s%s %s<input_data>%s %s<cluster_dir>%s %s[options]%s\n\n",
           ansi_bold_green, progname, ansi_reset,
           ansi_color_magenta, ansi_reset,
           ansi_color_magenta, ansi_reset,
           ansi_color_grey, ansi_reset);

    printf("%sDESCRIPTION%s\n", ansi_bold_cyan, ansi_reset);
    printf("  Identifies the k-nearest neighbors for each frame in a dataset using\n");
    printf("  the cluster anchors and metric distance bounds generated by Pass 1 "
           "(gric-cluster).\n");
    printf("  Maintains a strictly bounded resident RAM footprint while pruning 95-99%%\n");
    printf("  of high-dimensional distance evaluations.\n\n");

    printf("%sOPTIONS%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %s-k%s %s<int>%s              Number of nearest neighbors to find "
           "(%sdefault:%s 10)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-o, --output%s %s<path>%s   Output file path "
           "(default: <cluster_dir>/knn_k<K>.[fits|txt])\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-dtmin%s %s<int>%s          Min frame index separation |i - j| >= dtmin "
           "(%sdefault:%s 1)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-past%s                 Search only among preceding frames (j < i)\n",
           ansi_color_green, ansi_reset);
    printf("  %s-future%s               Search only among subsequent frames (j > i)\n",
           ansi_color_green, ansi_reset);
    printf("  %s-eps%s %s<float>%s          (1+eps)-ANN relaxation slack factor "
           "(%sdefault:%s 0.0)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-rlim%s %s<float>%s         Maximum distance cutoff "
           "(ignore neighbors beyond rlim)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-nthreads%s %s<int>%s       Number of OpenMP worker threads "
           "(%sdefault:%s all CPU cores)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-fits%s                 Force FITS output format\n",
           ansi_color_green, ansi_reset);
    printf("  %s-txt%s                  Force ASCII text output format\n",
           ansi_color_green, ansi_reset);
    printf("  %s-progress%s             Display live progress bar\n",
           ansi_color_green, ansi_reset);
    printf("  %s-v, -vv%s               Verbosity level\n",
           ansi_color_green, ansi_reset);
    printf("  %s-h, --help%s            Show this help message\n\n",
           ansi_color_green, ansi_reset);

    printf("%sEXAMPLES%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %s$%s %s%s%s dataset.fits cluster_out/ -k 10 -dtmin 5\n",
           ansi_color_grey, ansi_reset, ansi_bold_green, progname, ansi_reset);
    printf("  %s$%s %s%s%s spiral.txt cluster_out/ -k 20 -eps 0.05 -progress\n\n",
           ansi_color_grey, ansi_reset, ansi_bold_green, progname, ansi_reset);
    cli_print_color_mode();
}

int main(
    int   argc,
    char *argv[])
{
    cli_colors_init();

    KnnConfig config;
    memset(&config, 0, sizeof(KnnConfig));
    config.k = 10;
    config.min_temporal_sep = 1; // Exclude self-matching by default
    config.output_format = KNN_FORMAT_AUTO;
    config.progress_mode = 0;
    config.verbose_level = 1;

    int arg_idx = 1;
    while (arg_idx < argc)
    {
        if (strcmp(argv[arg_idx], "-h") == 0 || strcmp(argv[arg_idx], "--help") == 0)
        {
            print_help(argv[0]);
            return 0;
        }
        else if (strcmp(argv[arg_idx], "-k") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.k = atoi(argv[++arg_idx]);
            }
            else
            {
                fprintf(stderr, "Error: -k requires an integer argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-o") == 0 || strcmp(argv[arg_idx], "--output") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.output_path = argv[++arg_idx];
            }
            else
            {
                fprintf(stderr, "Error: -o requires a path argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-dtmin") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.min_temporal_sep = atoi(argv[++arg_idx]);
            }
            else
            {
                fprintf(stderr, "Error: -dtmin requires an integer argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-past") == 0)
        {
            config.past_only = 1;
        }
        else if (strcmp(argv[arg_idx], "-future") == 0)
        {
            config.future_only = 1;
        }
        else if (strcmp(argv[arg_idx], "-eps") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.epsilon = atof(argv[++arg_idx]);
            }
            else
            {
                fprintf(stderr, "Error: -eps requires a float argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-rlim") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.rlim_cutoff = atof(argv[++arg_idx]);
            }
            else
            {
                fprintf(stderr, "Error: -rlim requires a float argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-nthreads") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.nthreads = atoi(argv[++arg_idx]);
            }
            else
            {
                fprintf(stderr, "Error: -nthreads requires an integer argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-fits") == 0)
        {
            config.output_format = KNN_FORMAT_FITS;
        }
        else if (strcmp(argv[arg_idx], "-txt") == 0)
        {
            config.output_format = KNN_FORMAT_TXT;
        }
        else if (strcmp(argv[arg_idx], "-progress") == 0)
        {
            config.progress_mode = 1;
        }
        else if (strcmp(argv[arg_idx], "-v") == 0)
        {
            config.verbose_level = 2;
        }
        else if (strcmp(argv[arg_idx], "-vv") == 0)
        {
            config.verbose_level = 3;
        }
        else if (argv[arg_idx][0] == '-')
        {
            fprintf(stderr, "Error: Unknown option '%s'\n", argv[arg_idx]);
            print_usage(argv[0]);
            return 1;
        }
        else
        {
            if (config.input_data_path == NULL)
            {
                config.input_data_path = argv[arg_idx];
            }
            else if (config.cluster_dir == NULL)
            {
                config.cluster_dir = argv[arg_idx];
            }
            else
            {
                fprintf(stderr, "Error: Too many positional arguments\n");
                print_usage(argv[0]);
                return 1;
            }
        }
        arg_idx++;
    } // while parsing arguments

    if (config.input_data_path == NULL || config.cluster_dir == NULL)
    {
        fprintf(stderr, "Error: Missing required arguments <input_data> and <cluster_dir>\n");
        print_usage(argv[0]);
        return 1;
    }

    if (config.k <= 0)
    {
        fprintf(stderr, "Error: k must be >= 1\n");
        return 1;
    }

    printf("%sStarting gric-knn: Out-of-Core Metric-Pruned k-NN Solver%s\n",
           ansi_bold_green, ansi_reset);
    printf("  Dataset:       %s\n", config.input_data_path);
    printf("  Cluster Dir:   %s\n", config.cluster_dir);
    printf("  k Neighbors:   %d\n", config.k);
    printf("  Min Temp Sep:  %d frames\n", config.min_temporal_sep);
    if (config.past_only)
    {
        printf("  Direction:     Past-only (j < i)\n");
    }
    else if (config.future_only)
    {
        printf("  Direction:     Future-only (j > i)\n");
    }
    else
    {
        printf("  Direction:     Bidirectional\n");
    }
    if (config.epsilon > 0.0)
    {
        printf("  ANN Epsilon:   %.4f\n", config.epsilon);
    }
    if (config.rlim_cutoff > 0.0)
    {
        printf("  Radius Cutoff: %.6f\n", config.rlim_cutoff);
    }
    printf("\n");

    struct timespec load_start, load_end;
    clock_gettime(CLOCK_MONOTONIC, &load_start);

    KnnModel model;
    if (knn_model_load(config.cluster_dir, config.input_data_path, &model) != 0)
    {
        fprintf(stderr, "Error: Failed to load cluster model from '%s'\n", config.cluster_dir);
        return 1;
    }

    clock_gettime(CLOCK_MONOTONIC, &load_end);
    double load_time_ms = (load_end.tv_sec - load_start.tv_sec) * 1000.0 +
                          (load_end.tv_nsec - load_start.tv_nsec) / 1000000.0;

    printf("Loaded Pass 1 Model in %.2f ms:\n", load_time_ms);
    printf("  Total Frames:    %ld\n", model.total_dataset_frames);
    printf("  Total Clusters:  %d", model.num_clusters);
    if (model.num_super_clusters > 0)
    {
        printf(" (%d super-clusters)\n", model.num_super_clusters);
    }
    else
    {
        printf("\n");
    }
    printf("  Frame Dimension: %ld x %ld (%ld elements)\n\n",
           model.frame_width, model.frame_height, model.frame_elements);

    KnnResults results;
    memset(&results, 0, sizeof(KnnResults));
    KnnTelemetry telemetry;
    memset(&telemetry, 0, sizeof(KnnTelemetry));

    if (knn_run_search(&config, &model, &results, &telemetry) != 0)
    {
        fprintf(stderr, "Error: k-NN search failed\n");
        knn_model_free(&model);
        return 1;
    }

    struct timespec write_start, write_end;
    clock_gettime(CLOCK_MONOTONIC, &write_start);

    if (knn_write_results(&config, &model, &results) != 0)
    {
        fprintf(stderr, "Error: Failed to write results\n");
    }

    clock_gettime(CLOCK_MONOTONIC, &write_end);
    double write_time_ms = (write_end.tv_sec - write_start.tv_sec) * 1000.0 +
                           (write_end.tv_nsec - write_start.tv_nsec) / 1000000.0;
    uint64_t total_brute_force = (uint64_t)model.total_dataset_frames *
                                 (uint64_t)model.total_dataset_frames;
    double prune_pct = 100.0 * (1.0 - (double)telemetry.framedist_calls /
                                       (double)total_brute_force);
    double fps = (telemetry.time_search_ms > 0.0) ?
                 (double)model.total_dataset_frames / (telemetry.time_search_ms / 1000.0) : 0.0;

    printf("\n%sgric-knn Search Summary:%s\n", ansi_bold_cyan, ansi_reset);
    printf("  Total Query Frames:        %ld\n", model.total_dataset_frames);
    printf("  Framedist Computations:    %lu (vs %lu brute-force)\n",
           (unsigned long)telemetry.framedist_calls, (unsigned long)total_brute_force);
    printf("  Metric Pruning Efficiency: %s%.2f%%%s calls pruned!\n",
           ansi_bold_green, prune_pct, ansi_reset);
    if (telemetry.level0_super_clusters_pruned > 0)
    {
        printf("  Level 0 Super-Clusters:    %lu pruned\n",
               (unsigned long)telemetry.level0_super_clusters_pruned);
    }
    printf("  Level 1 Clusters Pruned:   %lu\n", (unsigned long)telemetry.level1_clusters_pruned);
    printf("  Level 2 Anchors Pruned:    %lu\n", (unsigned long)telemetry.level2_anchors_pruned);
    printf("  Level 3 Annular Pruned:    %lu\n", (unsigned long)telemetry.level3_annular_pruned);
    printf("  Temporal Exclusions:       %lu\n", (unsigned long)telemetry.temporal_pruned);
    printf("  Search Wall Time:          %.2f ms (%.1f fps)\n", telemetry.time_search_ms, fps);
    printf("  Output Write Time:         %.2f ms\n", write_time_ms);
    printf("%sCompleted successfully.%s\n", ansi_bold_green, ansi_reset);

    knn_results_free(&results);
    knn_model_free(&model);
    return 0;
}
