/**
 * @file main.c
 * @brief Entry point for gric-knn: Out-of-Core Metric-Pruned k-NN Solver.
 */

#define _POSIX_C_SOURCE 200809L
#include "knn_defs.h"
#include "knn_engine.h"
#include "knn_loader.h"
#include "knn_writer.h"
#include "shared/cli_colors.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

static void print_usage(
    const char *progname)
{
    fprintf(stderr, "Usage: %s <input_data> <cluster_dir> [options]\n", progname);
}

static void print_help(
    const char *progname)
{
    printf("%sNAME%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %sgric-knn%s - Out-of-core metric-pruned k-nearest neighbors solver\n\n",
           ansi_bold_green, ansi_reset);

    printf("%sUSAGE%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %s%s%s %s<input_data>%s %s<cluster_dir>%s %s[options]%s\n\n",
           ansi_bold_green, progname, ansi_reset,
           ansi_color_magenta, ansi_reset,
           ansi_color_magenta, ansi_reset,
           ansi_color_grey, ansi_reset);

    printf("%sDESCRIPTION%s\n", ansi_bold_cyan, ansi_reset);
    printf("  Identifies the k-nearest neighbors for each frame in a dataset using\n");
    printf("  the cluster anchors and metric distance bounds generated by Pass 1 "
           "(gric-cluster).\n");
    printf("  Maintains a strictly bounded resident RAM footprint while pruning 95-99%%\n");
    printf("  of high-dimensional distance evaluations.\n\n");

    printf("%sOPTIONS%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %s-query%s %s<path>%s         External query dataset (cross-dataset k-NN mode)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-k%s %s<int>%s              Number of nearest neighbors to find "
           "(%sdefault:%s 10)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-o, --output%s %s<path>%s   Output file path "
           "(default: <cluster_dir>/knn_k<K>.[fits|txt])\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-dtmin%s %s<int>%s          Min frame index separation |i - j| >= dtmin "
           "(%sdefault:%s 1)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-past%s                 Search only among preceding frames (j < i)\n",
           ansi_color_green, ansi_reset);
    printf("  %s-future%s               Search only among subsequent frames (j > i)\n",
           ansi_color_green, ansi_reset);
    printf("  %s-eps%s %s<float>%s          (1+eps)-ANN relaxation slack factor "
           "(%sdefault:%s 0.0)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-rlim%s %s<float>%s         Maximum distance cutoff "
           "(ignore neighbors beyond rlim)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-nthreads%s %s<int>%s       Number of OpenMP worker threads "
           "(%sdefault:%s all CPU cores)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-fits%s                 Force FITS output format\n",
           ansi_color_green, ansi_reset);
    printf("  %s-txt%s                  Force ASCII text output format\n",
           ansi_color_green, ansi_reset);
    printf("  %s-multipivot%s, %s-multi_pivot%s Enable Multi-Anchor Pivot Bounding (AESA)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-angular%s, %s--angular%s       Enable Angular Cosine Directional Bounding\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-angular%s, %s--no-angular%s Disable Angular Cosine Directional Bounding\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-trajectory%s, %s--trajectory%s   Enable Trajectory Momentum\n"
           "                                (for smooth trajectories)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-trajectory%s             Disable Trajectory Momentum (default)\n",
           ansi_color_green, ansi_reset);
    printf("  %s-no-reciprocal%s         Disable Symmetric Distance Reciprocal Push\n",
           ansi_color_green, ansi_reset);
    printf("  %s-approx%s, %s--approx%s         Fast Approximate Graph Search "
           "(10-20 evals/query)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-ef-search%s %s<L>%s       Search pool / heap size (default: 2*k in approx)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-progress%s             Display live progress bar\n",
           ansi_color_green, ansi_reset);
    printf("  %s-double%s, %s--double%s         Run computations in 64-bit double precision "
           "(%sdefault:%s float)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-sq8%s, %s--sq8%s               Enable 8-bit scalar quantization filtering "
           "(%sdefault:%s on)\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset,
           ansi_color_cyan, ansi_reset);
    printf("  %s-no-sq8%s, %s--no-sq8%s         Disable 8-bit scalar quantization filtering\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-sq8-save%s %s<path>%s      Save quantized dataset to sidecar file\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-sq8-load%s %s<path>%s      Load quantized dataset from sidecar file\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-sq16%s, %s--sq16%s             Enable 16-bit scalar quantization filtering\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-sq16%s, %s--no-sq16%s       Disable 16-bit scalar quantization filtering\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-sq16-save%s %s<path>%s     Save 16-bit quantized dataset to sidecar file\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-sq16-load%s %s<path>%s     Load 16-bit quantized dataset from sidecar file\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-no-batch-dist%s          Disable multi-vector SIMD batch distance\n",
           ansi_color_green, ansi_reset);
    printf("  %s-prof%s %s<path>%s          Explicit dataset profile file (.gricprof)\n",
           ansi_color_green, ansi_reset, ansi_color_magenta, ansi_reset);
    printf("  %s-no-prof%s, %s--no-prof%s       Disable auto-loading of .gricprof file\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-mutual%s, %s--no-mutual%s   Disable knn_mutual_dists.bin calculation/output\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-no-txt%s, %s--no-txt%s         Disable ASCII knn_results.txt output\n",
           ansi_color_green, ansi_reset, ansi_color_green, ansi_reset);
    printf("  %s-v, -vv%s               Verbosity level\n",
           ansi_color_green, ansi_reset);
    printf("  %s-h, --help%s            Show this help message\n\n",
           ansi_color_green, ansi_reset);

    printf("%sEXAMPLES%s\n", ansi_bold_cyan, ansi_reset);
    printf("  %s$%s %s%s%s dataset.fits cluster_out/ -k 10 -dtmin 5\n",
           ansi_color_grey, ansi_reset, ansi_bold_green, progname, ansi_reset);
    printf("  %s$%s %s%s%s spiral.txt cluster_out/ -k 20 -eps 0.05 -progress\n",
           ansi_color_grey, ansi_reset, ansi_bold_green, progname, ansi_reset);
    printf("  %s$%s %s%s%s train_A.txt cluster_out/ -query test_C.txt -k 10\n\n",
           ansi_color_grey, ansi_reset, ansi_bold_green, progname, ansi_reset);
    cli_print_color_mode();
}

int main(
    int   argc,
    char *argv[])
{
    cli_colors_init();

    KnnConfig config;
    memset(&config, 0, sizeof(KnnConfig));
    config.k = 50;
    config.min_temporal_sep = 1; // Exclude self-matching by default
    config.output_format = KNN_FORMAT_AUTO;
    config.progress_mode = 0;
    config.verbose_level = 1;
    config.use_reciprocal = 1; // Enabled by default for bidirectional search
    config.use_angular_bound = 1; // Enabled by default for directional pruning
    config.use_trajectory = 0; // Disabled by default; enable for smooth trajectories
    config.use_sq8 = 1; // Enabled by default for 8-bit metric pre-filtering
    config.use_batch_dist = 1; // Enabled by default for multi-vector SIMD batching

    int k_explicitly_set = 0;
    int dtmin_explicitly_set = 0;

    int arg_idx = 1;
    while (arg_idx < argc)
    {
        if (strcmp(argv[arg_idx], "-h") == 0 || strcmp(argv[arg_idx], "--help") == 0)
        {
            print_help(argv[0]);
            return 0;
        }
        else if (strcmp(argv[arg_idx], "-query") == 0 || strcmp(argv[arg_idx], "--query") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.query_data_path = argv[++arg_idx];
            }
            else
            {
                fprintf(stderr, "Error: -query requires a path argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-k") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.k = atoi(argv[++arg_idx]);
                k_explicitly_set = 1;
            }
            else
            {
                fprintf(stderr, "Error: -k requires an integer argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-o") == 0 || strcmp(argv[arg_idx], "--output") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.output_path = argv[++arg_idx];
            }
            else
            {
                fprintf(stderr, "Error: -o requires a path argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-dtmin") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.min_temporal_sep = atoi(argv[++arg_idx]);
                dtmin_explicitly_set = 1;
            }
            else
            {
                fprintf(stderr, "Error: -dtmin requires an integer argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-past") == 0)
        {
            config.past_only = 1;
        }
        else if (strcmp(argv[arg_idx], "-future") == 0)
        {
            config.future_only = 1;
        }
        else if (strcmp(argv[arg_idx], "-eps") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.epsilon = atof(argv[++arg_idx]);
            }
            else
            {
                fprintf(stderr, "Error: -eps requires a float argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-rlim") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.rlim_cutoff = atof(argv[++arg_idx]);
            }
            else
            {
                fprintf(stderr, "Error: -rlim requires a float argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-nthreads") == 0)
        {
            if (arg_idx + 1 < argc)
            {
                config.nthreads = atoi(argv[++arg_idx]);
            }
            else
            {
                fprintf(stderr, "Error: -nthreads requires an integer argument\n");
                return 1;
            }
        }
        else if (strcmp(argv[arg_idx], "-fits") == 0)
        {
            config.output_format = KNN_FORMAT_FITS;
        }
        else if (strcmp(argv[arg_idx], "-txt") == 0)
        {
            config.output_format = KNN_FORMAT_TXT;
        }
        else if (strcmp(argv[arg_idx], "-multipivot") == 0 ||
                 strcmp(argv[arg_idx], "--multipivot") == 0 ||
                 strcmp(argv[arg_idx], "-multi_pivot") == 0 ||
                 strcmp(argv[arg_idx], "--multi-pivot") == 0)
        {
            config.use_multi_pivot = 1;
        }
        else if (strcmp(argv[arg_idx], "-no-multipivot") == 0 ||
                 strcmp(argv[arg_idx], "-no_multipivot") == 0)
        {
            config.use_multi_pivot = 0;
        }
        else if (strcmp(argv[arg_idx], "-angular") == 0 ||
                 strcmp(argv[arg_idx], "--angular") == 0 ||
                 strcmp(argv[arg_idx], "-direction") == 0 ||
                 strcmp(argv[arg_idx], "--direction") == 0)
        {
            config.use_angular_bound = 1;
        }
        else if (strcmp(argv[arg_idx], "-no-angular") == 0 ||
                 strcmp(argv[arg_idx], "--no-angular") == 0 ||
                 strcmp(argv[arg_idx], "-no-direction") == 0 ||
                 strcmp(argv[arg_idx], "--no-direction") == 0)
        {
            config.use_angular_bound = 0;
        }
        else if (strcmp(argv[arg_idx], "-trajectory") == 0 ||
                 strcmp(argv[arg_idx], "--trajectory") == 0)
        {
            config.use_trajectory = 1;
        }
        else if (strcmp(argv[arg_idx], "-no-trajectory") == 0 ||
                 strcmp(argv[arg_idx], "--no-trajectory") == 0 ||
                 strcmp(argv[arg_idx], "-notrajectory") == 0)
        {
            config.use_trajectory = 0;
        }
        else if (strcmp(argv[arg_idx], "-reciprocal") == 0 ||
                 strcmp(argv[arg_idx], "--reciprocal") == 0)
        {
            config.use_reciprocal = 1;
        }
        else if (strcmp(argv[arg_idx], "-no-reciprocal") == 0 ||
                 strcmp(argv[arg_idx], "--no-reciprocal") == 0 ||
                 strcmp(argv[arg_idx], "-noreciprocal") == 0)
        {
            config.use_reciprocal = 0;
        }
        else if (strcmp(argv[arg_idx], "-approx") == 0 ||
                 strcmp(argv[arg_idx], "--approx") == 0 ||
                 strcmp(argv[arg_idx], "-fast") == 0 ||
                 strcmp(argv[arg_idx], "--fast") == 0)
        {
            config.approx_mode = 1;
        }
        else if (strcmp(argv[arg_idx], "-ef-search") == 0 ||
                 strcmp(argv[arg_idx], "--ef-search") == 0 ||
                 strcmp(argv[arg_idx], "-ef") == 0)
        {
            if (arg_idx + 1 >= argc)
            {
                fprintf(stderr, "Error: -ef-search requires an integer argument\n");
                return 1;
            }
            config.ef_search = atoi(argv[++arg_idx]);
        }
        else if (strcmp(argv[arg_idx], "-progress") == 0)
        {
            config.progress_mode = 1;
        }
        else if (strcmp(argv[arg_idx], "-double") == 0 ||
                 strcmp(argv[arg_idx], "--double") == 0)
        {
            config.use_double = 1;
        }
        else if (strcmp(argv[arg_idx], "-sq8") == 0 ||
                 strcmp(argv[arg_idx], "--sq8") == 0)
        {
            config.use_sq8 = 1;
            config.use_sq16 = 0;
        }
        else if (strcmp(argv[arg_idx], "-no-sq8") == 0 ||
                 strcmp(argv[arg_idx], "--no-sq8") == 0 ||
                 strcmp(argv[arg_idx], "-nosq8") == 0)
        {
            config.use_sq8 = 0;
        }
        else if (strcmp(argv[arg_idx], "-sq8-save") == 0 ||
                 strcmp(argv[arg_idx], "--sq8-save") == 0)
        {
            if (arg_idx + 1 >= argc)
            {
                fprintf(stderr, "Error: -sq8-save requires a filepath argument\n");
                return 1;
            }
            config.use_sq8 = 1;
            config.use_sq16 = 0;
            config.sq8_save_path = argv[++arg_idx];
        }
        else if (strcmp(argv[arg_idx], "-sq8-load") == 0 ||
                 strcmp(argv[arg_idx], "--sq8-load") == 0)
        {
            if (arg_idx + 1 >= argc)
            {
                fprintf(stderr, "Error: -sq8-load requires a filepath argument\n");
                return 1;
            }
            config.use_sq8 = 1;
            config.use_sq16 = 0;
            config.sq8_load_path = argv[++arg_idx];
        }
        else if (strcmp(argv[arg_idx], "-sq8-approx") == 0 ||
                 strcmp(argv[arg_idx], "--sq8-approx") == 0)
        {
            config.use_sq8 = 1;
            config.use_sq16 = 0;
            config.sq8_approx = 1;
        }
        else if (strcmp(argv[arg_idx], "-sq16") == 0 ||
                 strcmp(argv[arg_idx], "--sq16") == 0)
        {
            config.use_sq16 = 1;
            config.use_sq8 = 0;
        }
        else if (strcmp(argv[arg_idx], "-no-sq16") == 0 ||
                 strcmp(argv[arg_idx], "--no-sq16") == 0 ||
                 strcmp(argv[arg_idx], "-nosq16") == 0)
        {
            config.use_sq16 = 0;
        }
        else if (strcmp(argv[arg_idx], "-sq16-save") == 0 ||
                 strcmp(argv[arg_idx], "--sq16-save") == 0)
        {
            if (arg_idx + 1 >= argc)
            {
                fprintf(stderr, "Error: -sq16-save requires a filepath argument\n");
                return 1;
            }
            config.use_sq16 = 1;
            config.use_sq8 = 0;
            config.sq16_save_path = argv[++arg_idx];
        }
        else if (strcmp(argv[arg_idx], "-sq16-load") == 0 ||
                 strcmp(argv[arg_idx], "--sq16-load") == 0)
        {
            if (arg_idx + 1 >= argc)
            {
                fprintf(stderr, "Error: -sq16-load requires a filepath argument\n");
                return 1;
            }
            config.use_sq16 = 1;
            config.use_sq8 = 0;
            config.sq16_load_path = argv[++arg_idx];
        }
        else if (strcmp(argv[arg_idx], "-sq16-approx") == 0 ||
                 strcmp(argv[arg_idx], "--sq16-approx") == 0)
        {
            config.use_sq16 = 1;
            config.use_sq8 = 0;
            config.sq16_approx = 1;
        }
        else if (strcmp(argv[arg_idx], "-batch-dist") == 0 ||
                 strcmp(argv[arg_idx], "--batch-dist") == 0 ||
                 strcmp(argv[arg_idx], "-batchdist") == 0)
        {
            config.use_batch_dist = 1;
        }
        else if (strcmp(argv[arg_idx], "-no-batch-dist") == 0 ||
                 strcmp(argv[arg_idx], "--no-batch-dist") == 0 ||
                 strcmp(argv[arg_idx], "-nobatchdist") == 0)
        {
            config.use_batch_dist = 0;
        }
        else if (strcmp(argv[arg_idx], "-prof") == 0 ||
                 strcmp(argv[arg_idx], "--prof") == 0)
        {
            if (arg_idx + 1 >= argc)
            {
                fprintf(stderr, "Error: -prof requires a filepath argument\n");
                return 1;
            }
            config.prof_filename = argv[++arg_idx];
        }
        else if (strcmp(argv[arg_idx], "-no-prof") == 0 ||
                 strcmp(argv[arg_idx], "--no-prof") == 0)
        {
            config.no_prof = 1;
        }
        else if (strcmp(argv[arg_idx], "-no-mem") == 0 ||
                 strcmp(argv[arg_idx], "--no-mem") == 0 ||
                 strcmp(argv[arg_idx], "-no-cache") == 0)
        {
            config.no_cache_dataset = 1;
        }
        else if (strcmp(argv[arg_idx], "-no-mutual") == 0 ||
                 strcmp(argv[arg_idx], "--no-mutual") == 0 ||
                 strcmp(argv[arg_idx], "-no_mutual") == 0 ||
                 strcmp(argv[arg_idx], "-nomutual") == 0)
        {
            config.no_mutual = 1;
        }
        else if (strcmp(argv[arg_idx], "-no-txt") == 0 ||
                 strcmp(argv[arg_idx], "--no-txt") == 0 ||
                 strcmp(argv[arg_idx], "-no_txt") == 0 ||
                 strcmp(argv[arg_idx], "-notxt") == 0)
        {
            config.no_txt = 1;
        }
        else if (strcmp(argv[arg_idx], "-v") == 0)
        {
            config.verbose_level = 2;
        }
        else if (strcmp(argv[arg_idx], "-vv") == 0)
        {
            config.verbose_level = 3;
        }
        else if (argv[arg_idx][0] == '-')
        {
            fprintf(stderr, "Error: Unknown option '%s'\n", argv[arg_idx]);
            print_usage(argv[0]);
            return 1;
        }
        else
        {
            if (config.input_data_path == NULL)
            {
                config.input_data_path = argv[arg_idx];
            }
            else if (config.cluster_dir == NULL)
            {
                config.cluster_dir = argv[arg_idx];
            }
            else
            {
                fprintf(stderr, "Error: Too many positional arguments\n");
                print_usage(argv[0]);
                return 1;
            }
        }
        arg_idx++;
    } // while parsing arguments

    if (config.input_data_path == NULL || config.cluster_dir == NULL)
    {
        fprintf(stderr, "Error: Missing required arguments <input_data> and <cluster_dir>\n");
        print_usage(argv[0]);
        return 1;
    }

    if (config.k <= 0)
    {
        fprintf(stderr, "Error: k must be >= 1\n");
        return 1;
    }

    if (config.query_data_path != NULL)
    {
        if (!k_explicitly_set)
        {
            config.k = 30; // Default k=30 for cross-dataset query mode
        }
        if (!dtmin_explicitly_set)
        {
            config.min_temporal_sep = 0; // Cross-dataset query has no temporal self-exclusion
        }
        config.use_reciprocal = 0;
    }

    printf("%sStarting gric-knn: Out-of-Core Metric-Pruned k-NN Solver%s\n",
           ansi_bold_green, ansi_reset);
    printf("  Dataset (A):   %s\n", config.input_data_path);
    printf("  Cluster Dir:   %s\n", config.cluster_dir);
    if (config.query_data_path != NULL)
    {
        printf("  Query Set (C): %s (Cross-Dataset Mode)\n", config.query_data_path);
    }
    printf("  k Neighbors:   %d\n", config.k);
    if (config.query_data_path == NULL)
    {
        printf("  Min Temp Sep:  %d frames\n", config.min_temporal_sep);
        if (config.past_only)
        {
            printf("  Direction:     Past-only (j < i)\n");
            config.use_reciprocal = 0;
        }
        else if (config.future_only)
        {
            printf("  Direction:     Future-only (j > i)\n");
            config.use_reciprocal = 0;
        }
        else
        {
            printf("  Direction:     Bidirectional\n");
        }
    }
    if (config.epsilon > 0.0)
    {
        printf("  ANN Epsilon:   %.4f\n", config.epsilon);
    }
    if (config.rlim_cutoff > 0.0)
    {
        printf("  Radius Cutoff: %.6f\n", config.rlim_cutoff);
    }
    if (config.use_multi_pivot)
    {
        printf("  Multi-Pivot:   Enabled (AESA/LAESA Indexing)\n");
    }
    if (config.use_reciprocal)
    {
        printf("  Reciprocal:    Enabled (Symmetric d(i,j)=d(j,i))\n");
    }
    if (config.use_angular_bound)
    {
        printf("  Angular Bound: Enabled (Directional Cosine Bounding)\n");
    }
    if (config.query_data_path != NULL && config.use_trajectory)
    {
        printf("  Trajectory:    Enabled (Sequential Heap & Seed Warm-Start)\n");
    }
    if (config.approx_mode)
    {
        int eff_ef = (config.ef_search > 0) ? config.ef_search : 2 * config.k;
        printf("  Approx Search: Enabled (ef_search = %d)\n", eff_ef);
    }
    else if (config.ef_search > 0)
    {
        printf("  Search Pool:   ef_search = %d\n", config.ef_search);
    }
    if (config.use_sq16)
    {
        printf("  SQ16 Filtering: Enabled (%s)\n",
               config.sq16_approx ? "Relaxed Approx Mode" : "Exact Lower-Bound Mode");
    }
    else if (config.use_sq8)
    {
        printf("  SQ8 Filtering: Enabled (%s)\n",
               config.sq8_approx ? "Relaxed Approx Mode" : "Exact Lower-Bound Mode");
    }
    printf("  Precision:     %s\n",
           config.use_double ? "64-bit Double Precision" : "32-bit Single Precision (Default)");
    printf("\n");

    struct timespec load_start, load_end;
    clock_gettime(CLOCK_MONOTONIC, &load_start);

    KnnModel model;
    if (knn_model_load(config.cluster_dir, config.input_data_path, &model,
                       config.use_double) != 0)
    {
        fprintf(stderr, "Error: Failed to load cluster model from '%s'\n", config.cluster_dir);
        return 1;
    }

    knn_model_cache_dataset(&model, &config);

    // Profile auto-discovery and loading
    char auto_prof_path[1024];
    const char *prof_to_load = config.prof_filename;
    if (prof_to_load == NULL && !config.no_prof)
    {
        if (gric_profile_find_auto(config.input_data_path,
                                   auto_prof_path,
                                   sizeof(auto_prof_path)))
        {
            prof_to_load = auto_prof_path;
        }
        else
        {
            char cluster_dir_prof[1024];
            snprintf(cluster_dir_prof, sizeof(cluster_dir_prof),
                     "%s/dataset.gricprof", config.cluster_dir);
            FILE *fchk = fopen(cluster_dir_prof, "r");
            if (fchk != NULL)
            {
                fclose(fchk);
                snprintf(auto_prof_path, sizeof(auto_prof_path), "%s", cluster_dir_prof);
                prof_to_load = auto_prof_path;
            }
        }
    }

    if (prof_to_load != NULL)
    {
        if (gric_profile_read_json(prof_to_load, &model.profile) == 0)
        {
            model.has_profile = 1;
            printf("%s[PROFILE]%s Auto-loaded dataset profile: %s\n",
                   ansi_bold_cyan, ansi_reset, prof_to_load);
            if (model.profile.use_sq16)
            {
                printf("  Range: [%.4f, %.4f], SQ16 scale: %.6f, suggested rlim: %.4f\n",
                       model.profile.sq16_params.min_val, model.profile.sq16_params.max_val,
                       model.profile.sq16_params.scale, model.profile.rlim_recommended);
            }
            else
            {
                printf("  Range: [%.4f, %.4f], SQ8 scale: %.6f, suggested rlim: %.4f\n",
                       model.profile.sq8_params.min_val, model.profile.sq8_params.max_val,
                       model.profile.sq8_params.scale, model.profile.rlim_recommended);
            }
        }
    }

    if (config.use_sq16)
    {
        if (knn_model_build_or_load_sq16(&model, &config) != 0)
        {
            fprintf(stderr, "Error: Failed to initialize SQ16 dataset buffer\n");
            knn_model_free(&model);
            return 1;
        }
    }
    else if (config.use_sq8)
    {
        if (knn_model_build_or_load_sq8(&model, &config) != 0)
        {
            fprintf(stderr, "Error: Failed to initialize SQ8 dataset buffer\n");
            knn_model_free(&model);
            return 1;
        }
    }

    clock_gettime(CLOCK_MONOTONIC, &load_end);
    double load_time_ms = (load_end.tv_sec - load_start.tv_sec) * 1000.0 +
                          (load_end.tv_nsec - load_start.tv_nsec) / 1000000.0;

    printf("Loaded Pass 1 Model in %.2f ms:\n", load_time_ms);
    printf("  Total Frames:    %ld\n", model.total_dataset_frames);
    printf("  Total Clusters:  %d", model.num_clusters);
    if (model.num_super_clusters > 0)
    {
        printf(" (%d super-clusters)\n", model.num_super_clusters);
    }
    else
    {
        printf("\n");
    }
    printf("  Frame Dimension: %ld x %ld (%ld elements)\n\n",
           model.frame_width, model.frame_height, model.frame_elements);

    KnnResults results;
    memset(&results, 0, sizeof(KnnResults));
    KnnTelemetry telemetry;
    memset(&telemetry, 0, sizeof(KnnTelemetry));

    if (knn_run_search(&config, &model, &results, &telemetry) != 0)
    {
        fprintf(stderr, "Error: k-NN search failed\n");
        knn_model_free(&model);
        return 1;
    }

    struct timespec write_start, write_end;
    clock_gettime(CLOCK_MONOTONIC, &write_start);

    if (knn_write_results(&config, &model, &results) != 0)
    {
        fprintf(stderr, "Error: Failed to write results\n");
    }

    clock_gettime(CLOCK_MONOTONIC, &write_end);
    double write_time_ms = (write_end.tv_sec - write_start.tv_sec) * 1000.0 +
                           (write_end.tv_nsec - write_start.tv_nsec) / 1000000.0;
    long total_queries = (results.num_queries > 0) ? results.num_queries :
                                                     model.total_dataset_frames;
    uint64_t total_brute_force = (uint64_t)total_queries *
                                 (uint64_t)model.total_dataset_frames;
    double prune_pct = 100.0 * (1.0 - (double)telemetry.framedist_calls /
                                       (double)total_brute_force);
    double fps = (telemetry.time_search_ms > 0.0) ?
                 (double)total_queries / (telemetry.time_search_ms / 1000.0) : 0.0;

    printf("\n%sgric-knn Search Summary:%s\n", ansi_bold_cyan, ansi_reset);
    printf("  Total Query Frames:        %ld\n", total_queries);
    printf("  Framedist Computations:    %lu (vs %lu brute-force)\n",
           (unsigned long)telemetry.framedist_calls, (unsigned long)total_brute_force);
    printf("  Metric Pruning Efficiency: %s%.4f%%%s calls pruned!\n",
           ansi_bold_green, prune_pct, ansi_reset);
    if (telemetry.level0_super_clusters_pruned > 0)
    {
        printf("  Level 0 Super-Clusters:    %lu pruned\n",
               (unsigned long)telemetry.level0_super_clusters_pruned);
    }
    printf("  Level 1 Clusters Pruned:   %lu\n", (unsigned long)telemetry.level1_clusters_pruned);
    printf("  Level 2 Anchors Pruned:    %lu\n", (unsigned long)telemetry.level2_anchors_pruned);
    printf("  Level 3 Annular Pruned:    %lu\n", (unsigned long)telemetry.level3_annular_pruned);
    if (config.use_sq16)
    {
        uint64_t total_sq16_pruned = telemetry.sq16_members_pruned +
                                     telemetry.sq16_graph_pruned;
        printf("  SQ16 Evaluations:          %lu\n",
               (unsigned long)telemetry.sq16_evaluations);
        printf("  SQ16 Lower-Bound Pruned:   %lu\n",
               (unsigned long)total_sq16_pruned);
        printf("  SQ16 Member Pruned:        %lu\n",
               (unsigned long)telemetry.sq16_members_pruned);
        printf("  SQ16 Graph Pruned:         %lu\n",
               (unsigned long)telemetry.sq16_graph_pruned);
    }
    else if (config.use_sq8)
    {
        uint64_t total_sq8_pruned = telemetry.sq8_members_pruned +
                                    telemetry.sq8_graph_pruned;
        printf("  SQ8 Evaluations:           %lu\n",
               (unsigned long)telemetry.sq8_evaluations);
        printf("  SQ8 Lower-Bound Pruned:    %lu\n",
               (unsigned long)total_sq8_pruned);
        printf("  SQ8 Member Pruned:         %lu\n",
               (unsigned long)telemetry.sq8_members_pruned);
        printf("  SQ8 Graph Pruned:          %lu\n",
               (unsigned long)telemetry.sq8_graph_pruned);
    }
    if (telemetry.graph_seeds_evaluated > 0)
    {
        printf("  Graph Seeds Evaluated:     %lu\n",
               (unsigned long)telemetry.graph_seeds_evaluated);
    }
    if (telemetry.graph_edges_pruned > 0)
    {
        printf("  Graph Edges Pruned:        %lu\n",
               (unsigned long)telemetry.graph_edges_pruned);
    }
    printf("  Multi-Pivot Pruned:        %lu\n",
           (unsigned long)telemetry.multi_pivot_pruned);
    if (telemetry.angular_pruned > 0)
    {
        uint64_t total_graph_cands = telemetry.graph_seeds_evaluated +
                                     telemetry.graph_edges_pruned +
                                     telemetry.angular_pruned;
        double ang_pct = (total_graph_cands > 0) ?
            100.0 * (double)telemetry.angular_pruned / (double)total_graph_cands : 0.0;
        printf("  Angular Cosine Pruned:     %lu (%.1f%% of graph edges)\n",
               (unsigned long)telemetry.angular_pruned, ang_pct);
    }
    if (telemetry.trajectory_warmstarts > 0)
    {
        printf("  Trajectory Warmstarts:     %lu queries (%.1f%%)\n",
               (unsigned long)telemetry.trajectory_warmstarts,
               100.0 * (double)telemetry.trajectory_warmstarts /
                   (double)telemetry.total_queries);
    }
    if (telemetry.global_containment_hits > 0)
    {
        printf("  Global Containment Hits:   %lu queries (%.1f%%)\n",
               (unsigned long)telemetry.global_containment_hits,
               100.0 * (double)telemetry.global_containment_hits /
                   (double)telemetry.total_queries);
    }
    if (telemetry.reciprocal_reused > 0)
    {
        printf("  Reciprocal Reused:         %lu\n",
               (unsigned long)telemetry.reciprocal_reused);
    }
    printf("  Temporal Exclusions:       %lu\n", (unsigned long)telemetry.temporal_pruned);
    printf("  Search Wall Time:          %.2f ms (%.1f fps)\n", telemetry.time_search_ms, fps);
    printf("  Output Write Time:         %.2f ms\n", write_time_ms);
    printf("%sCompleted successfully.%s\n", ansi_bold_green, ansi_reset);

    knn_results_free(&results);
    knn_model_free(&model);
    return 0;
}
