# cmake/GricBuildInfo.cmake
# Generates build/gric_build_info.h with git version and commit metadata.
# Only touches the file if the content changed to preserve build timestamps.

if (NOT DEFINED SOURCE_DIR)
    set(SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
endif()
if (NOT DEFINED BINARY_DIR)
    set(BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}")
endif()

find_package(Git QUIET)

set(GIT_DESCRIBE "unknown")
set(GIT_HEAD "unknown")

if (GIT_FOUND AND EXISTS "${SOURCE_DIR}/.git")
    execute_process(
        COMMAND ${GIT_EXECUTABLE} describe --always --dirty
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_DESCRIBE_OUT
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE GIT_DESC_RES
    )
    if (GIT_DESC_RES EQUAL 0 AND NOT "${GIT_DESCRIBE_OUT}" STREQUAL "")
        set(GIT_DESCRIBE "${GIT_DESCRIBE_OUT}")
    endif()

    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-parse HEAD
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_HEAD_OUT
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE GIT_HEAD_RES
    )
    if (GIT_HEAD_RES EQUAL 0 AND NOT "${GIT_HEAD_OUT}" STREQUAL "")
        set(GIT_HEAD "${GIT_HEAD_OUT}")
    endif()
endif()

set(OUT_FILE "${BINARY_DIR}/gric_build_info.h")
set(NEW_CONTENT "/* Auto-generated by cmake/GricBuildInfo.cmake - DO NOT EDIT */
#ifndef GRIC_BUILD_INFO_H
#define GRIC_BUILD_INFO_H

#define GRIC_GIT_DESCRIBE \"${GIT_DESCRIBE}\"
#define GRIC_GIT_HEAD     \"${GIT_HEAD}\"

#endif /* GRIC_BUILD_INFO_H */
")

set(WRITE_NEEDED TRUE)
if (EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" OLD_CONTENT)
    if ("${OLD_CONTENT}" STREQUAL "${NEW_CONTENT}")
        set(WRITE_NEEDED FALSE)
    endif()
endif()

if (WRITE_NEEDED)
    file(WRITE "${OUT_FILE}" "${NEW_CONTENT}")
endif()
